asd:(.((`Chart
    (0 0.3192652 0.7444795 0.76288 0.7058086 0.4989252 0.385982 0.203236 0.09029283 0 1
     0.9043935 0.1097923 0 0 0 0 0 0 0 0 0
     0.02380813 0.4263413 0 0 0 0 0 0 0 0 0
     0.0717984 0.1446013 0.2521282 0.07995844 0.01183232 0 0 0 0 0 0
     0 0 0.003392381 0.02275507 0.04717302 0.09104458 0.1237986 0.1767956 0.2095496 0.3 0
     0 0 0 0.1344065 0.235186 0.4100302 0.4902194 0.6199683 0.7001575 0.7 0
     0 0 0 0 0 0 0 0 0 0 0.0)
    .,(`j
       .((`c;`gbar;)
         (`border;0;)
         (`wy;1.0;)
         (`rownames
          `J `I `H `G `F `E `D `C `B `A `"0"
          )
         (`colnames
          `"Bonds Corp BBB 00 05" `"Bonds Corp AAA 00 05" `"Bonds Corp AA 00 05" `"Government 05 10" `"US Stock" `"Bonds Corp A 20 up" `"Government 20 up"
          )
         (`pi
          .,(`obsspacing;100;)
          )
         (`axis
          .,(`label
             .((`x;"Point";)
               (`y;"Allocation";))
             )
          )
         (`aoi
          .,(`drawgrid
             .((`x;1;)
               (`y;1;))
             )
          )
         (`acoi
          .,(`gridcolor
             .((`x;210210210;)
               (`y;210210210;))
             )
          )
         (`oi
          .((`stacked;1;)
            (`horizontal;0;)
            (`drawlegend;0;))
          )
         (`vcoi
          .,(`areacolor
             220220220 202202202 184184184 165165165 144144144 121121121 90090090
             )
          )
         (`afi
          .((`axislabelfont
             (`x `"Helvetica 1 12"
              `y `"Helvetica 1 12")
             )
            (`ticklabelfont
             (`x `"Helvetica 0 12"
              `y `"Helvetica 0 12")
             ))
          )
         (`mousemode
          ,`leftclick `select
          )
         (`anno
          ((0 1
            0 2
            0 3
            0 4
            0 5
            0 6
            0 7
            0 8
            0 10
            1 0
            1 1
            2 1
            3 0
            3 1
            3 2
            3 3
            4 5
            4 6
            4 7
            4 8
            4 9
            5 3
            5 4
            5 5
            5 6
            5 7
            5 8
            5 9)
           ("Bonds Corp BBB 00 05"
            "Bonds Corp BBB 00 05"
            "Bonds Corp BBB 00 05"
            "Bonds Corp BBB 00 05"
            "Bonds Corp BBB 00 05"
            "Bonds Corp BBB 00 05"
            "Bonds Corp BBB 00 05"
            "Bonds Corp BBB 00 05"
            "Bonds Corp BBB 00 05"
            "Bonds Corp AAA 00 05"
            "Bonds Corp AAA 00 05"
            "Bonds Corp AA 00 05"
            "Government 05 10"
            "Government 05 10"
            "Government 05 10"
            "Government 05 10"
            "US Stock"
            "US Stock"
            "US Stock"
            "US Stock"
            "US Stock"
            "Bonds Corp A 20 up"
            "Bonds Corp A 20 up"
            "Bonds Corp A 20 up"
            "Bonds Corp A 20 up"
            "Bonds Corp A 20 up"
            "Bonds Corp A 20 up"
            "Bonds Corp A 20 up"))
          )
         (`annoalign
          ((0 1
            0 2
            0 3
            0 4
            0 5
            0 6
            0 7
            0 8
            0 10
            1 0
            1 1
            2 1
            3 0
            3 1
            3 2
            3 3
            4 5
            4 6
            4 7
            4 8
            4 9
            5 3
            5 4
            5 5
            5 6
            5 7
            5 8
            5 9)
           `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c `c)
          )
         (`annofg
          ((0 1
            0 2
            0 3
            0 4
            0 5
            0 6
            0 7
            0 8
            0 10
            1 0
            1 1
            2 1
            3 0
            3 1
            3 2
            3 3
            4 5
            4 6
            4 7
            4 8
            4 9
            5 3
            5 4
            5 5
            5 6
            5 7
            5 8
            5 9)
           0 0 0 0 0 0 0 0 0 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255 255255255)
          )
         (`annofont
          ((0 1
            0 2
            0 3
            0 4
            0 5
            0 6
            0 7
            0 8
            0 10
            1 0
            1 1
            2 1
            3 0
            3 1
            3 2
            3 3
            4 5
            4 6
            4 7
            4 8
            4 9
            5 3
            5 4
            5 5
            5 6
            5 7
            5 8
            5 9)
           `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12")
          ))
       ))
   (`Label
    .((`t
       .()
       .,(`j
          .((`c;`panel;)
            (`border;0;)
            (`bg;255255255;)
            (`wy;0.5;))
          ))
      (`a
       1
       .,(`j
          .((`c;`check;)
            (`l;`"All Active";)
            (`lbg;255255255;)
            (`lfg;0;)
            (`wy;1e-010;)
            (`e;1;)
            (`t;{
    e:Output[`tab;`Asset_Allocation_Chart;`Label;~ACF;`j;`e]
    Output[`tab;`Asset_Allocation_Chart;`Label;ACF]:e*`. .j.v
    set_allocation_annotation[]
    };))
          ))
      (`a0
       1
       .((`j
          .((`c;`check;)
            (`l;`"Bonds Corp BBB 00 05";)
            (`lbg;220220220;)
            (`lfg;0;)
            (`wy;1e-010;)
            (`e;1;)
            (`t;{
    set_allocation_annotation[]
    };))
          )
         (`annodict
          .((`anno
             ((0 1
               0 2
               0 3
               0 4
               0 5
               0 6
               0 7
               0 8
               0 10)
              ("Bonds Corp BBB 00 05"
               "Bonds Corp BBB 00 05"
               "Bonds Corp BBB 00 05"
               "Bonds Corp BBB 00 05"
               "Bonds Corp BBB 00 05"
               "Bonds Corp BBB 00 05"
               "Bonds Corp BBB 00 05"
               "Bonds Corp BBB 00 05"
               "Bonds Corp BBB 00 05"))
             )
            (`annoalign
             ((0 1
               0 2
               0 3
               0 4
               0 5
               0 6
               0 7
               0 8
               0 10)
              `c `c `c `c `c `c `c `c `c)
             )
            (`annofg
             ((0 1
               0 2
               0 3
               0 4
               0 5
               0 6
               0 7
               0 8
               0 10)
              0 0 0 0 0 0 0 0 0)
             )
            (`annofont
             ((0 1
               0 2
               0 3
               0 4
               0 5
               0 6
               0 7
               0 8
               0 10)
              `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12")
             ))
          )))
      (`a1
       1
       .((`j
          .((`c;`check;)
            (`l;`"Bonds Corp AAA 00 05";)
            (`lbg;202202202;)
            (`lfg;255255255;)
            (`wy;1e-010;)
            (`e;1;)
            (`t;{
    set_allocation_annotation[]
    };))
          )
         (`annodict
          .((`anno
             ((1 0
               1 1)
              ("Bonds Corp AAA 00 05"
               "Bonds Corp AAA 00 05"))
             )
            (`annoalign
             ((1 0
               1 1)
              `c `c)
             )
            (`annofg
             ((1 0
               1 1)
              255255255 255255255)
             )
            (`annofont
             ((1 0
               1 1)
              `"Helvetica 0 12" `"Helvetica 0 12")
             ))
          )))
      (`a2
       1
       .((`j
          .((`c;`check;)
            (`l;`"Bonds Corp AA 00 05";)
            (`lbg;184184184;)
            (`lfg;255255255;)
            (`wy;1e-010;)
            (`e;1;)
            (`t;{
    set_allocation_annotation[]
    };))
          )
         (`annodict
          .((`anno
             (,2 1
              ,"Bonds Corp AA 00 05")
             )
            (`annoalign
             (,2 1
              ,`c)
             )
            (`annofg
             (,2 1
              ,255255255)
             )
            (`annofont
             (,2 1
              ,`"Helvetica 0 12")
             ))
          )))
      (`a3
       1
       .((`j
          .((`c;`check;)
            (`l;`"Government 05 10";)
            (`lbg;165165165;)
            (`lfg;255255255;)
            (`wy;1e-010;)
            (`e;1;)
            (`t;{
    set_allocation_annotation[]
    };))
          )
         (`annodict
          .((`anno
             ((3 0
               3 1
               3 2
               3 3)
              ("Government 05 10"
               "Government 05 10"
               "Government 05 10"
               "Government 05 10"))
             )
            (`annoalign
             ((3 0
               3 1
               3 2
               3 3)
              `c `c `c `c)
             )
            (`annofg
             ((3 0
               3 1
               3 2
               3 3)
              255255255 255255255 255255255 255255255)
             )
            (`annofont
             ((3 0
               3 1
               3 2
               3 3)
              `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12")
             ))
          )))
      (`a4
       1
       .((`j
          .((`c;`check;)
            (`l;`"US Stock";)
            (`lbg;144144144;)
            (`lfg;255255255;)
            (`wy;1e-010;)
            (`e;1;)
            (`t;{
    set_allocation_annotation[]
    };))
          )
         (`annodict
          .((`anno
             ((4 5
               4 6
               4 7
               4 8
               4 9)
              ("US Stock"
               "US Stock"
               "US Stock"
               "US Stock"
               "US Stock"))
             )
            (`annoalign
             ((4 5
               4 6
               4 7
               4 8
               4 9)
              `c `c `c `c `c)
             )
            (`annofg
             ((4 5
               4 6
               4 7
               4 8
               4 9)
              255255255 255255255 255255255 255255255 255255255)
             )
            (`annofont
             ((4 5
               4 6
               4 7
               4 8
               4 9)
              `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12")
             ))
          )))
      (`a5
       1
       .((`j
          .((`c;`check;)
            (`l;`"Bonds Corp A 20 up";)
            (`lbg;121121121;)
            (`lfg;255255255;)
            (`wy;1e-010;)
            (`e;1;)
            (`t;{
    set_allocation_annotation[]
    };))
          )
         (`annodict
          .((`anno
             ((5 3
               5 4
               5 5
               5 6
               5 7
               5 8
               5 9)
              ("Bonds Corp A 20 up"
               "Bonds Corp A 20 up"
               "Bonds Corp A 20 up"
               "Bonds Corp A 20 up"
               "Bonds Corp A 20 up"
               "Bonds Corp A 20 up"
               "Bonds Corp A 20 up"))
             )
            (`annoalign
             ((5 3
               5 4
               5 5
               5 6
               5 7
               5 8
               5 9)
              `c `c `c `c `c `c `c)
             )
            (`annofg
             ((5 3
               5 4
               5 5
               5 6
               5 7
               5 8
               5 9)
              255255255 255255255 255255255 255255255 255255255 255255255 255255255)
             )
            (`annofont
             ((5 3
               5 4
               5 5
               5 6
               5 7
               5 8
               5 9)
              `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12" `"Helvetica 0 12")
             ))
          )))
      (`a6
       0
       .,(`j
          .((`c;`check;)
            (`l;`"Government 20 up";)
            (`lbg;90090090;)
            (`lfg;255255255;)
            (`wy;1e-010;)
            (`e;0;)
            (`t;{
    set_allocation_annotation[]
    };))
          ))
      (`b
       .()
       .,(`j
          .((`c;`panel;)
            (`border;0;)
            (`bg;255255255;)
            (`wy;0.5;))
          )))
    .,(`j
       .((`c;`panel;)
         (`border;0;)
         (`bg;255255255;)
         (`wx;1e-010;)
         (`a
          (,`t
           ,`a
           ,`a0
           ,`a1
           ,`a2
           ,`a3
           ,`a4
           ,`a5
           ,`a6
           ,`b)
          ))
       )))
 .,(`j
    .((`c;`panel;)
      (`a
       ,`Chart `Label
       )
      (`l;"Asset Allocation Chart";))
    ))

p:asd[0]
p.:asd[1]

p..j.l:"EFA Asset Allocation Chart Completed Optimization"


.j.Java{
  .j.c `p
}

p..j.close:{_exit 0}
p..j.z: {
  if[1~.k[`autoExit];_exit 0]
  }