.V..Hash_Location:(0;`A;`System;`Random;`Hidden)
.S:,_n
.S[0;`A;`System;`Random;`Hidden]:.((`CIR_State
   .((`V0;303;.())
     (`V1;370;.())
     (`V2;437;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Economic_Variables
      )
     (`V;;)
     (`P;;)))
  (`Economy
   .((`US;2178;.())
     (`DE;1223;.())
     (`GB;1025;.())
     (`CH;1423;.())
     (`AU;2292;.())
     (`CA;954;.())
     (`JP;1966;.())
     (`DK;1625;.())
     (`NO;1903;.())
     (`SE;1238;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      `Economic_Variables `Financial_Markets `Inner_Loop_Projections
      )
     (`V;;)
     (`P;;)))
  (`Currency
   .((`USD;12955;.())
     (`EUR;10383;.())
     (`GBP;134;.())
     (`CHF;21178;.())
     (`AUD;13069;.())
     (`CAD;11731;.())
     (`JPY;41476;.())
     (`DKK;43825;.())
     (`NOK;44103;.())
     (`SEK;43438;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Economic_Variables
      )
     (`V;;)
     (`P;;)))
  (`Common_Stock_Index
   .((`US_Large_Cap;11307;.())
     (`US_Mid_Cap;24182;.())
     (`US_Broad_Cap;29956;.())
     (`US_Small_Cap;62811;.())
     (`US_Other_Sector;31790;.())
     (`DE_Large_Cap;10352;.())
     (`DE_Mid_Cap;23227;.())
     (`DE_Broad_Cap;29001;.())
     (`DE_Small_Cap;61856;.())
     (`DE_Other_Sector;30835;.())
     (`GB_Large_Cap;10154;.())
     (`GB_Mid_Cap;23029;.())
     (`GB_Broad_Cap;28803;.())
     (`GB_Small_Cap;61658;.())
     (`GB_Other_Sector;30637;.())
     (`CH_Large_Cap;10552;.())
     (`CH_Mid_Cap;23427;.())
     (`CH_Broad_Cap;29201;.())
     (`CH_Small_Cap;62056;.())
     (`CH_Other_Sector;31035;.())
     (`AU_Large_Cap;11421;.())
     (`AU_Mid_Cap;24296;.())
     (`AU_Broad_Cap;30070;.())
     (`AU_Small_Cap;62925;.())
     (`AU_Other_Sector;31904;.())
     (`CA_Large_Cap;10083;.())
     (`CA_Mid_Cap;22958;.())
     (`CA_Broad_Cap;28732;.())
     (`CA_Small_Cap;61587;.())
     (`CA_Other_Sector;30566;.())
     (`JP_Large_Cap;11095;.())
     (`JP_Mid_Cap;23970;.())
     (`JP_Broad_Cap;29744;.())
     (`JP_Small_Cap;62599;.())
     (`JP_Other_Sector;31578;.())
     (`DK_Large_Cap;10754;.())
     (`DK_Mid_Cap;23629;.())
     (`DK_Broad_Cap;29403;.())
     (`DK_Small_Cap;62258;.())
     (`DK_Other_Sector;31237;.())
     (`NO_Large_Cap;11032;.())
     (`NO_Mid_Cap;23907;.())
     (`NO_Broad_Cap;29681;.())
     (`NO_Small_Cap;62536;.())
     (`NO_Other_Sector;31515;.())
     (`SE_Large_Cap;10367;.())
     (`SE_Mid_Cap;23242;.())
     (`SE_Broad_Cap;29016;.())
     (`SE_Small_Cap;61871;.())
     (`SE_Other_Sector;30850;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      `Economic_Variables `Inner_Loop_Projections
      )
     (`V;;)
     (`P;;)))
  (`Index_Item
   .((`Price;28298;.())
     (`Dividend_Yield;37332;.())
     (`Variance;26544;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Economic_Variables
      )
     (`V;;)
     (`P;;)))
  (`Jump_Component
   .((`Number;1576;.())
     (`Size;5828;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      `Economic_Variables `Inner_Loop_Projections
      )
     (`V;;)
     (`P;;)))
  (`Corporate_Bond_Rating
   .((`AAA;63798;.())
     (`AA;952;.())
     (`A;14;.())
     (`BBB;2819;.())
     (`High_Yield;38473;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Economic_Variables
      )
     (`V;;)
     (`P;;)))
  (`Default_Type
   .((`Stress;9929;.())
     (`Fool;30563;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Financial_Markets
      )
     (`V;;)
     (`P;;)))
  (`Inflation_Index
   .((`Consumer_Prices;63676;.())
     (`New_Vehicle;5442;.())
     (`Motors;45507;.())
     (`Professional;64886;.())
     (`Hospital;3047;.())
     (`Construction;22236;.())
     (`Wages;13104;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Economic_Variables
      )
     (`V;;)
     (`P;;)))
  (`Property
   .((`US_Office;29573;.())
     (`US_Retail;57328;.())
     (`US_Residential;48869;.())
     (`DE_Office;28618;.())
     (`DE_Retail;56373;.())
     (`DE_Residential;47914;.())
     (`GB_Office;28420;.())
     (`GB_Retail;56175;.())
     (`GB_Residential;47716;.())
     (`CH_Office;28818;.())
     (`CH_Retail;56573;.())
     (`CH_Residential;48114;.())
     (`AU_Office;29687;.())
     (`AU_Retail;57442;.())
     (`AU_Residential;48983;.())
     (`CA_Office;28349;.())
     (`CA_Retail;56104;.())
     (`CA_Residential;47645;.())
     (`JP_Office;29361;.())
     (`JP_Retail;57116;.())
     (`JP_Residential;48657;.())
     (`DK_Office;29020;.())
     (`DK_Retail;56775;.())
     (`DK_Residential;48316;.())
     (`NO_Office;29298;.())
     (`NO_Retail;57053;.())
     (`NO_Residential;48594;.())
     (`SE_Office;28633;.())
     (`SE_Retail;56388;.())
     (`SE_Residential;47929;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Economic_Variables
      )
     (`V;;)
     (`P;;)))
  (`Property_Item
   .((`Price;28298;.())
     (`Rent;6688;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Economic_Variables
      )
     (`V;;)
     (`P;;)))
  (`Premium_Based_Expense_Item
   .((`CBE;16287;.())
     (`TLF;21463;.())
     (`UWE;17712;.())
     (`MGT;18431;.())
     (`PHD;12213;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Acquisition_Costs
      )
     (`V;;)
     (`P;;)))
  (`Loss_Item
   .((`Loss;56714;.())
     (`ALAE;38781;.())
     (`SS;2176;.())
     (`ULAE;38801;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Property_Casualty
      )
     (`V;;)
     (`P;;)))
  (`Library_Pattern
   .,(`Library_Pattern_1;44370;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Library_Pattern;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Greek
   .,(`Greek_1;3758;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Greek;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Function
   .,(`Function_1;31040;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Function;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Transform
   .,(`Transform_1;28414;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Transform;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Life_Table
   .,(`Life_Table_1;7869;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Life_Table;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Compression
   .,(`Compression_1;52928;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Compression;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Inner_Loop
   .,(`Inner_Loop_1;25355;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Inner_Loop_Projections
      )
     (`V;;)
     (`U;`Inner_Loop;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Risk_Class
   .,(`Risk_Class_1;38992;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Risk_Class;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Asset_Class
   .((`All_Investments;25987;.())
     (`All_Investments_ex_Affiliates;35392;.())
     (`Alternative;31580;.())
     (`Alternative_Bonds;49269;.())
     (`Alternative_HGB;43961;.())
     (`Alternative_Indices;12560;.())
     (`Bonds_Affiliate;44671;.())
     (`Bonds_Corp;5127;.())
     (`Bonds_Corp_A;14661;.())
     (`Bonds_Corp_AA;64797;.())
     (`Bonds_Corp_AAA;16037;.())
     (`Bonds_Corp_AAA_00_01;21542;.())
     (`Bonds_Corp_AAA_01_02;12382;.())
     (`Bonds_Corp_AAA_02_05;23887;.())
     (`Bonds_Corp_AAA_05_10;26231;.())
     (`Bonds_Corp_AAA_10_20;29848;.())
     (`Bonds_Corp_AAA_20_up;39171;.())
     (`Bonds_Corp_AA_00_01;17928;.())
     (`Bonds_Corp_AA_01_02;46897;.())
     (`Bonds_Corp_AA_02_05;58402;.())
     (`Bonds_Corp_AA_05_10;63971;.())
     (`Bonds_Corp_AA_10_20;44462;.())
     (`Bonds_Corp_AA_20_up;43623;.())
     (`Bonds_Corp_A_00_01;30590;.())
     (`Bonds_Corp_A_01_02;10292;.())
     (`Bonds_Corp_A_02_05;17058;.())
     (`Bonds_Corp_A_05_10;43015;.())
     (`Bonds_Corp_A_10_20;4576;.())
     (`Bonds_Corp_A_20_up;40755;.())
     (`Bonds_Corp_A_plus;34045;.())
     (`Bonds_Corp_BBB;20594;.())
     (`Bonds_Corp_BBB_00_01;26099;.())
     (`Bonds_Corp_BBB_01_02;24135;.())
     (`Bonds_Corp_BBB_02_05;13809;.())
     (`Bonds_Corp_BBB_05_10;30788;.())
     (`Bonds_Corp_BBB_10_20;34405;.())
     (`Bonds_Corp_BBB_20_up;43728;.())
     (`Bonds_Corp_Default;42541;.())
     (`Bonds_Corp_High_Yield;47566;.())
     (`Bonds_Corp_High_Yield_00_01;64153;.())
     (`Bonds_Corp_High_Yield_01_02;52021;.())
     (`Bonds_Corp_High_Yield_02_05;515;.())
     (`Bonds_Corp_High_Yield_05_10;35924;.())
     (`Bonds_Corp_High_Yield_10_20;9215;.())
     (`Bonds_Corp_High_Yield_20_up;52056;.())
     (`Bonds_FRN;41860;.())
     (`Bonds_Indices;30196;.())
     (`Bonds_Inflation;43403;.())
     (`Bonds_Model;27096;.())
     (`Bonds_Pfandbriefe;42213;.())
     (`Bonds_Risk_Free;14622;.())
     (`Bonds_Schuldschein;9126;.())
     (`Bonds_State_GO;61369;.())
     (`Bonds_State_GO_and_Corp_A_plus;39031;.())
     (`Bonds_Treasury;63937;.())
     (`Common_Stock;3071;.())
     (`Common_Stock_Affiliate;20856;.())
     (`Common_Stock_Indices;57094;.())
     (`Common_Stock_Unaffiliated;33307;.())
     (`Derivatives;14693;.())
     (`Derivatives_Equity;53499;.())
     (`Derivatives_Interest;9623;.())
     (`Fixed_Income;41709;.())
     (`Fixed_Income_HGB;16649;.())
     (`Fixed_Income_Tax_Exempt;2361;.())
     (`Fixed_Income_Taxable;36219;.())
     (`Investments_in_Affiliates;61401;.())
     (`Mortgages;61832;.())
     (`Mortgages_Direct;54992;.())
     (`Mortgages_Securitized;32342;.())
     (`Preferred;649;.())
     (`Preferred_A;35927;.())
     (`Preferred_AA;877;.())
     (`Preferred_AAA;54908;.())
     (`Preferred_Affiliate;22284;.())
     (`Preferred_BBB;15764;.())
     (`Preferred_Default;1007;.())
     (`Preferred_High_Yield;39620;.())
     (`Preferred_Indices;41862;.())
     (`Preferred_Model;42431;.())
     (`Preferred_Unaffiliated;29821;.())
     (`Property;51284;.())
     (`Property_Indices;27435;.())
     (`Property_Model;5174;.())
     (`Stock;48175;.())
     (`Stock_Affiliated;18859;.())
     (`Stock_Unaffiliated;48751;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Asset_Class;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`HGB_Equalization_Line
   .((`Allgemeine_Unfall;54763;.())
     (`LUR_Haftpflicht;52280;.())
     (`KFZ_Haftpflicht;21650;.())
     (`KFZ_Kasko;12534;.())
     (`LUR_Kasko;43164;.())
     (`Beistandsleistung;26341;.())
     (`Rechtsschutz;39211;.())
     (`Allgemeine_Haftpflicht;8210;.())
     (`Feuer_Industrie;60436;.())
     (`Feuer_Landwirtschaft;43431;.())
     (`Feuer_Sonstige;25233;.())
     (`Verbundene_Hausrat;53158;.())
     (`Verbundene_Wohngebaeude;53648;.())
     (`Feuer_Indirekt;9159;.())
     (`Haftpflicht_Indirekt;45281;.())
     (`Kraftfahrt_Indirekt;34515;.())
     (`LUR_Kasko_Indirekt;9659;.())
     (`Unfall_Indirekt;26834;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`HGB_Equalization_Line;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Claim_Cost_Index
   .,(`Claim_Cost_Index_1;39057;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Property_Casualty
      )
     (`V;;)
     (`U;`Claim_Cost_Index;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Financing_Instrument
   .,(`Financing_Instrument_1;36389;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Financing_Instrument;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Supplemental_Model
   .,(`Supplemental_Model_1;2982;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Supplemental_Model;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Portfolio
   .,(`Portfolio_1;32942;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Portfolio;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Entity
   .,(`Entity_1;28553;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Financing
      )
     (`V;;)
     (`U;`Entity;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`User_Value
   .,(`User_Value_1;15607;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`User_Values
      )
     (`V;;)
     (`U;`User_Value;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Consolidation
   .,(`Consolidation_1;54834;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Consolidation;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Peril
   .,(`Peril_1;50690;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Property_Casualty
      )
     (`V;;)
     (`U;`Peril;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Product
   .,(`Product_1;8437;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      `Property_Casualty `Future_Written `Acquisition_Costs `Reinsurance
      )
     (`V;;)
     (`U;`Product;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Product_Group
   .,(`Product_Group_1;39485;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Product_Group;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Treaty
   .,(`Treaty_1;45765;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Reinsurance
      )
     (`V;;)
     (`U;`Treaty;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Treaty_Group
   .,(`Treaty_Group_1;50141;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Treaty_Group;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Life_Product
   .,(`Life_Product_1;35712;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Life_Insurance
      )
     (`V;;)
     (`U;`Life_Product;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Plan
   .,(`Plan_1;21123;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Plan;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Counterparty
   .,(`Counterparty_1;24486;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Property_Casualty
      )
     (`V;;)
     (`U;`Counterparty;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`State
   .,(`State_1;48139;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`State;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Transition
   .,(`Transition_1;41503;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Transition;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Lookup
   .,(`Lookup_1;18786;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Lookup;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Return_Class
   .,(`Return_Class_1;17607;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`Return_Class;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`Market_Index
   .((`Barra_E0;28369;.())
     (`Barra_EC;57941;.())
     (`Barra_TR;51441;.())
     (`CISDMFOF_E0;37135;.())
     (`CISDMFOF_EC;47867;.())
     (`CISDMFOF_TR;27247;.())
     (`SPLPEQTR_E0;42083;.())
     (`SPLPEQTR_EC;52815;.())
     (`SPLPEQTR_TR;32195;.())
     (`MSCI_E0;51582;.())
     (`MSCI_EC;16810;.())
     (`MSCI_TR;62686;.())
     (`LPXEUR;3282;.())
     (`JP_IPD;23928;.())
     (`US_NCREIF;24551;.())
     (`UK_IPD;23604;.())
     (`CH_IPD;23385;.())
     (`CA_IPD;22916;.())
     (`AU_IPD;24254;.())
     (`SE_IPD;23200;.())
     (`DK_IPD;23587;.())
     (`NO_IPD;23865;.())
     (`US_Large_Cap;11307;.())
     (`US_Mid_Cap;24182;.())
     (`US_Small_Cap;62811;.())
     (`US_Other_Sector;31790;.())
     (`DE_Large_Cap;10352;.())
     (`DE_Other_Sector;30835;.())
     (`GB_Large_Cap;10154;.())
     (`CH_Large_Cap;10552;.())
     (`CA_Large_Cap;10083;.())
     (`AU_Large_Cap;11421;.())
     (`JP_Large_Cap;11095;.())
     (`DK_Large_Cap;10754;.())
     (`NO_Large_Cap;11032;.())
     (`SE_Large_Cap;10367;.()))
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B
      ,`Economic_Variables
      )
     (`V;;)
     (`U;`Market_Index;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`User_Relative_Value
   .,(`User_Relative_Value_1;25772;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`User_Relative_Value;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`QIS4_Region
   .,(`QIS4_Region_1;57344;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`QIS4_Region;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;)))
  (`QIS5_Region
   .,(`QIS5_Region_1;30427;.())
   .((`j
      .((`c;`Slot;)
        (`f;;)
        (`popup
         .((`Reset_Default;;)
           (`Resolve_Duplicates;;))
         ))
      )
     (`B;`Developer;)
     (`V;;)
     (`U;`QIS5_Region;)
     (`J
      .((`C;;)
        (`D;;)
        (`R;;)
        (`A;;)
        (`L;;))
      )
     (`P;;))))

.G.axes:.((`Library_Pattern
   .((`Homeowners_Farmowners;1;)
     (`Private_Passenger_Auto_Liability;1;)
     (`Commercial_Auto_Liability;1;)
     (`Workers_Compensation;1;)
     (`Commercial_Multi_Peril;1;)
     (`Medical_Malpractice_Occurrence;1;)
     (`Medical_Malpractice_Claims_Made;1;)
     (`Special_Liability;1;)
     (`Other_Liability_Occurrence;1;)
     (`Other_Liability_Claims_Made;1;)
     (`Fire_and_Allied_Lines_IM_EQ_Burglary;1;)
     (`Auto_Physical_Damage;1;)
     (`Fidelity_Surety;1;)
     (`Accident_Health_and_Credit;1;)
     (`International;1;)
     (`Reinsurance_Property;1;)
     (`Reinsurance_Liability;1;)
     (`Reinsurance_Finanacial;1;)
     (`Products_Liability_Occurrence;1;)
     (`Products_Liability_Claims_Made;1;)
     (`Mortgage_and_Financial_Guaranty;1;))
   )
  (`Greek
   .,(`Greek_1;1;)
   )
  (`Function
   .,(`Function_1;1;)
   )
  (`Transform
   .,(`Transform_1;1;)
   )
  (`Life_Table
   .,(`Life_Table_1;1;)
   )
  (`Compression
   .,(`Compression_1;1;)
   )
  (`Inner_Loop
   .,(`Inner_Loop_1;1;)
   )
  (`Risk_Class
   .,(`Risk_Class_1;1;)
   )
  (`Asset_Class
   .((`All_Investments;1;)
     (`All_Investments_ex_Affiliates;1;)
     (`Alternative;1;)
     (`Alternative_Bonds;1;)
     (`Alternative_HGB;1;)
     (`Alternative_Indices;1;)
     (`Bonds_Affiliate;1;)
     (`Bonds_Corp;1;)
     (`Bonds_Corp_A;1;)
     (`Bonds_Corp_AA;1;)
     (`Bonds_Corp_AAA;1;)
     (`Bonds_Corp_AAA_00_01;1;)
     (`Bonds_Corp_AAA_01_02;1;)
     (`Bonds_Corp_AAA_02_05;1;)
     (`Bonds_Corp_AAA_05_10;1;)
     (`Bonds_Corp_AAA_10_20;1;)
     (`Bonds_Corp_AAA_20_up;1;)
     (`Bonds_Corp_AA_00_01;1;)
     (`Bonds_Corp_AA_01_02;1;)
     (`Bonds_Corp_AA_02_05;1;)
     (`Bonds_Corp_AA_05_10;1;)
     (`Bonds_Corp_AA_10_20;1;)
     (`Bonds_Corp_AA_20_up;1;)
     (`Bonds_Corp_A_00_01;1;)
     (`Bonds_Corp_A_01_02;1;)
     (`Bonds_Corp_A_02_05;1;)
     (`Bonds_Corp_A_05_10;1;)
     (`Bonds_Corp_A_10_20;1;)
     (`Bonds_Corp_A_20_up;1;)
     (`Bonds_Corp_A_plus;1;)
     (`Bonds_Corp_BBB;1;)
     (`Bonds_Corp_BBB_00_01;1;)
     (`Bonds_Corp_BBB_01_02;1;)
     (`Bonds_Corp_BBB_02_05;1;)
     (`Bonds_Corp_BBB_05_10;1;)
     (`Bonds_Corp_BBB_10_20;1;)
     (`Bonds_Corp_BBB_20_up;1;)
     (`Bonds_Corp_Default;1;)
     (`Bonds_Corp_High_Yield;1;)
     (`Bonds_Corp_High_Yield_00_01;1;)
     (`Bonds_Corp_High_Yield_01_02;1;)
     (`Bonds_Corp_High_Yield_02_05;1;)
     (`Bonds_Corp_High_Yield_05_10;1;)
     (`Bonds_Corp_High_Yield_10_20;1;)
     (`Bonds_Corp_High_Yield_20_up;1;)
     (`Bonds_FRN;1;)
     (`Bonds_Indices;1;)
     (`Bonds_Inflation;1;)
     (`Bonds_Model;1;)
     (`Bonds_Pfandbriefe;1;)
     (`Bonds_Risk_Free;1;)
     (`Bonds_Schuldschein;1;)
     (`Bonds_State_GO;1;)
     (`Bonds_State_GO_and_Corp_A_plus;1;)
     (`Bonds_Treasury;1;)
     (`Common_Stock;1;)
     (`Common_Stock_Affiliate;1;)
     (`Common_Stock_Indices;1;)
     (`Common_Stock_Unaffiliated;1;)
     (`Derivatives;1;)
     (`Derivatives_Equity;1;)
     (`Derivatives_Interest;1;)
     (`Fixed_Income;1;)
     (`Fixed_Income_HGB;1;)
     (`Fixed_Income_Tax_Exempt;1;)
     (`Fixed_Income_Taxable;1;)
     (`Investments_in_Affiliates;1;)
     (`Mortgages;1;)
     (`Mortgages_Direct;1;)
     (`Mortgages_Securitized;1;)
     (`Preferred;1;)
     (`Preferred_A;1;)
     (`Preferred_AA;1;)
     (`Preferred_AAA;1;)
     (`Preferred_Affiliate;1;)
     (`Preferred_BBB;1;)
     (`Preferred_Default;1;)
     (`Preferred_High_Yield;1;)
     (`Preferred_Indices;1;)
     (`Preferred_Model;1;)
     (`Preferred_Unaffiliated;1;)
     (`Property;1;)
     (`Property_Indices;1;)
     (`Property_Model;1;)
     (`Stock;1;)
     (`Stock_Affiliated;1;)
     (`Stock_Unaffiliated;1;))
   )
  (`HGB_Equalization_Line
   .((`Allgemeine_Unfall;1;)
     (`LUR_Haftpflicht;1;)
     (`KFZ_Haftpflicht;1;)
     (`KFZ_Kasko;1;)
     (`LUR_Kasko;1;)
     (`Beistandsleistung;1;)
     (`Rechtsschutz;1;)
     (`Allgemeine_Haftpflicht;1;)
     (`Feuer_Industrie;1;)
     (`Feuer_Landwirtschaft;1;)
     (`Feuer_Sonstige;1;)
     (`Verbundene_Hausrat;1;)
     (`Verbundene_Wohngebaeude;1;)
     (`Feuer_Indirekt;1;)
     (`Haftpflicht_Indirekt;1;)
     (`Kraftfahrt_Indirekt;1;)
     (`LUR_Kasko_Indirekt;1;)
     (`Unfall_Indirekt;1;))
   )
  (`Claim_Cost_Index
   .,(`Claim_Cost_Index_1;1;)
   )
  (`Financing_Instrument
   .,(`Financing_Instrument_1;1;)
   )
  (`Supplemental_Model
   .,(`Supplemental_Model_1;1;)
   )
  (`Portfolio
   .,(`Portfolio_1;1;)
   )
  (`Entity
   .,(`Entity_1;1;)
   )
  (`User_Value
   .,(`User_Value_1;1;)
   )
  (`Consolidation
   .,(`Consolidation_1;1;)
   )
  (`Peril
   .,(`Peril_1;1;)
   )
  (`Product
   .,(`Product_1;1;)
   )
  (`Product_Group
   .,(`Product_Group_1;1;)
   )
  (`Treaty
   .,(`Treaty_1;1;)
   )
  (`Treaty_Group
   .,(`Treaty_Group_1;1;)
   )
  (`Life_Product
   .,(`Life_Product_1;1;)
   )
  (`Plan
   .,(`Plan_1;1;)
   )
  (`Counterparty
   .,(`Counterparty_1;1;)
   )
  (`State
   .,(`State_1;1;)
   )
  (`Transition
   .,(`Transition_1;1;)
   )
  (`Lookup
   .,(`Lookup_1;1;)
   )
  (`Return_Class
   .,(`Return_Class_1;1;)
   )
  (`Market_Index
   .((`Market_Index_1;0;)
     (`DE_Large_Cap;1;)
     (`DE_Other_Sector;1;))
   )
  (`User_Relative_Value
   .,(`User_Relative_Value_1;1;)
   )
  (`QIS4_Region
   .,(`QIS4_Region_1;1;)
   )
  (`QIS5_Region
   .,(`QIS5_Region_1;1;)
   ))

create_u:{[u]
  define_u (),u
  if[0<ja:#.k.Axes.tab..j.a; .j.c`.k.Axes]
  if[~ja; .j.ok.i["There are no flexible axes to edit"]]
  }
define_u:{[u]
  Axes.tab::.()
  create_u_tab'u
  Axes.tab..j.a::{x@<x}@u@&|/'{&/prune_b_'x}''.V..B[u]
  Axes.tab..j.tab::*u
  }
create_u_tab:{[u]
  bg:.j.Null; (.+(`w`m`j;236233216 171178195 238238238))[.p.Look_and_Feel]
  Axes.tab[u]:d:(+,/'2#'..G[`axes;u])@1 0
  Axes.hash[u]:.k.get_s .V..Hash_Location,u,_n
  Axes.tab[~u;`j;`f`c`s`u`cell`editor`cg`bg`sbg`sfg`fbg]:((-1$$:;-60$.l.ss@$:);`matrix;();(u_u_select;u_u[u]);(.,`c`check;);1 2;bg;bg;`scrollbarblue;0;`scrollbarblue)
  Axes.tab[~u;`j;`g]:(;)
  Axes.tab[~u;`j;`popup]:Axes..j.menu`Edit
  Axes.tab[~u;`j;`popup;`s1]:" "
  Axes.tab[~u;`j;`popup;`Copy`Paste]:.j`Copy`Paste
  Axes.tab[~u;`j;`popup.;`j;`async]:2
  Axes.tab[~u;`Log]:()
  Axes.tab[~u;`j;`t]:active_u
  Axes.tab[~u;`j;`s.;`j;`t]:active_u
  }
u_u:{[u;x;y]:[x~new:u_u_[u;(`..j.v)[1];x;y];x;rename_u[u;x;new]]}
u_u_:{[u;a;x;y]
  all:?,/u_Exclusive@&u _in/:u_Exclusive			/ all flexible axes which might conflict with element name
  full:.+(all;u_Reserved[all],'Axes.tab[all;1])			/ all names for all potential conflict axes
  :[~#r:unspace_u y;						e_u[x;"No name specified"]
    (s:`$r)_in R:a _dv x;					e_u[x;("'&0' in use";r)]
    (u _in u_Case)&#w:&(us:`$.j.uc s)=`$'.j.uc'R;		e_u[x;("'&0' in use in another case as '&1'";r;$R@w)]
    s _in(),u_Reserved u;					e_u[x;("'&0' is a reserved name";r)]
    (u _in u_Case)&us _in(),.j.uc'u_Reserved u;			e_u[x;("'&0' is a reserved name";$us)]
    s _in(),?,/full[all _dvl ,u];				e_u[x;("'&0' is used by companion axis &1";r;$*all@&s _in/:full[all])]
    (u _in u_Case)&us _in(),`$'.j.uc'?,/full[all _dvl ,u];	e_u[x;("'&0' is used in another case by companion axis &1";r;$*all@&s _in/:full[all])]
    ~variable_u r;						e_u[x;("'&0' is invalid:\nNames must begin with a-z, A-Z and contain only a-z, A-Z, _, 0-9";r)]
								s ] }
active_u:{
  if[_n~t:tab_u[];:_n]
  v:Axes.tab[t;1]
  c:Axes.tab[t;0]
  s:Axes.tab[~t;`j;`s]
/  `0:"s: ",(5:s),"\n"
/  `0:".j.v: ",(5:.j.v),"\n"
/  `0:".j.i: ",(5:.j.i),"\n"
  s:(*|:)'s@&*:'s
  if[~&/(#v)>s; `0:"Problem !!!\n"; :_n]
  cs:c s
  cn:c _di s
  Axes.toolbar[~`Append;`j;`e]:1
  if[~#s
    Axes.toolbar[~`Insert`Delete`Top`Up`Down`Bottom`With`Without`Only`Except;`j;`e]:0 ]
  if[#s
    Axes.toolbar[~`Insert	;`j;`e]:1
    Axes.toolbar[~`Delete	;`j;`e]:(1 _in cn)
    Axes.toolbar[~`Top`Up	;`j;`e]:~0 _in s
    Axes.toolbar[~`Down`Bottom	;`j;`e]:~(-1+#c)_in s
    Axes.toolbar[~`With		;`j;`e]:(0 _in cs)
    Axes.toolbar[~`Without	;`j;`e]:(1 _in cs)&1 _in cn
    Axes.toolbar[~`Only		;`j;`e]:(0 _in cs)|1 _in cn
    Axes.toolbar[~`Except	;`j;`e]:((1 _in cs)|0 _in cn)&0<#cn ]
  Axes.toolbar[~`Sort		;`j;`e]:~(!#v)~<v
  Axes.toolbar[~`All		;`j;`e]:0 _in c
  {Axes..j.menu..j.ne[1;Axes..j.menu..j.ne[0]?x]:Axes.toolbar[~y;`j;`e]}.'(	(`Edit`Append		;`Append)
										(`Edit`Insert		;`Insert)
										(`Edit`Append_Multiple_	;`Append)
										(`Edit`Delete		;`Delete)
										(`Order`Top		;`Top)
										(`Order`Up		;`Up)
										(`Order`Down		;`Down)
										(`Order`Bottom		;`Bottom)
										(`Order`Sort		;`Sort)
										(`Select`All		;`All)
										(`Select`With		;`With)
										(`Select`Without	;`Without)
										(`Select`Only		;`Only)
										(`Select`Except		;`Except))
  g:=Axes..j.menu..j.ne[0;;0]
  Axes..j.menu..j.ne[1;g[;0]]:|/'Axes..j.menu..j.ne[1;1_'g]
  .[`;(`k;`Axes;`tab;~t;`j;`s);{:[x~_n;x;x@&*:'x]}]
  }

variable_u:{[s]
  ~*@[.:;,(`$$s;);:] }
unspace_u:{[s]
  _ssr[.u.db _ssr[$s;"_";" "];" ";"_"] }
u_u_select:{
  :[~|/*.[`..j.v;.j.i;:;y]
    e_u[x;"At least one axis element must be selected"]
    y ] }
e_u:{
  .j.e y
  x }
w_u_hash:{
  .j.ok.w y
  x }
append_multiple_u:{ / append_multiple_u
  t:.j.v / save .j.v
  if[#n:.j.Input[,"1";"Number of new axis elements";"Append Multiple Axis Elements"]
    if[*r:.[0$;n;:]
      :.j.e"Number of new axis elements must be an integer."]
    if[~0<n:r 1
      :.j.e"Number of new axis elements must be positive."]
    .j.v:t / restore .j.v for use by append_u
    v:var_u u:tab_u[]
    n:{[n;u]
      v:$Axes.tab[u;1]; h:Axes.hash[u]; a:($u),"_"; r:0#`
      do[n; r,:new:new_u_[v;h;a]; v,:,$new; h,:.u.symbol_hash16 new]; r}[n;u]
    .j.app.row[v;((#n)#1;n)] / .j.app.row[v;(,1;,n;,h)]
    Axes.hash[u],:.u.symbol_hash16'n
    log_u[u;`Append]'n
    active_u[]
    ]
  }
copy_paste:{[a;c;p]
  status("Copying &0.&1 into &0.&2";a;c;p)
  q:0,'.u.treepaths get_s 0
  q@:&a~'get_s'{attr[x],`U}'q
  q@:&a~'get_s'{attr[x],`C}'q                    / ??? test this !!!
  q@:<#:'q
  i:0;do[#q;if[~(-1_ q i)_in i#q;copy_paste_ . q[i],/::[5=4:get_s q i;c,p;()]];i+:1]
  status"Copied"
  }
copy_paste_:{[i;j]
  copy i
  paste[paste_ref;1;j] } / ;reset_def 0,`A}
insert_u:{ / insert_u
  if[#i:idx_u u:tab_u[]
    v:var_u u
    do[#i
      n:new_u u
      h:.u.symbol_hash16[n]
      .j.ins.row[v;*i;(,1;,n)] / .j.ins.row[v;*i;(,1;,n;,h)]
      Axes.hash[u]:{(y#x),(,z),y _ x}[Axes.hash[u];*i;h]
      log_u[u;`Insert;n,*i] ] ] }
delete_u:{ / delete_u
  if[#i:idx_u u:tab_u[]
    v:var_u u
    m:. v
      if[empty_u . m _di\:i
        .j.del.row[v;i]
        Axes.hash[u]:Axes.hash[u] _di i
        log_u[u;`Delete]'m[1;i] ] ] }
empty_u:{[x;y] / empty_u
  r::[~#y;1;~|/x]
    if[r;.j.e"Cannot delete last axis element selected"]
  ~r }
append_u:{ / append_u
  v:var_u u:tab_u[]
  n:new_u u
  h:.u.symbol_hash16[n]
  .j.app.row[v;(,1;,n)] / .j.app.row[v;(,1;,n;,h)]
  Axes.hash[u],:h
  log_u[u;`Append;n]
  active_u[] }
rename_u:{ / rename_u
  log_u[x;`Rename;(y;z)]
  z }
all_u:{ / all_u
  .[v:var_u tab_u[];(0;);:;1]
  active_u[]
  }
with_u:{ / with_u
  if[(~#s)|_n~s:select_u v:var_u tab_u[]
    :.j.e"Nothing selected" ]
  .[v;(0;s);:;1]
  active_u[]
  }
without_u:{ / without_u
  if[(~#s)|_n~s:select_u v:var_u tab_u[]
    :.j.e"Nothing selected" ]
  if[~#(&*. v)_dvl s
    :.j.e"Cannot deselect all axis elements" ]
  .[v;(0;s);:;0]
  active_u[]
  }
only_u:{ / only_u
  if[(~#s)|_n~s:select_u v:var_u tab_u[]
    :.j.e"Nothing selected" ]
  .[v;(0;);:;(!#*. v)_lin s]
  active_u[]
  }
except_u:{ / except_u
  if[_n~s:select_u v:var_u tab_u[]
    :.j.e"Nothing selected" ]
  if[~|/b:~(!#*. v)_lin s
    :.j.e"Cannot deselect all axis elements"]
  .[v;(0;);:;b]
  active_u[]
  }
select_u:{[v] / select_u
  :[~(s:.[~v;`j`s])_in(;());s[;1]] }
log_u:{[u;f;a] / log_u
  Axes.tab[~u;`Log],:,(f;a) }
new_u:{[u] / new_u
  v:$Axes.tab[u;1]
  h:Axes.hash[u]
  a:($u),"_"
  new_u_[v;h;a]}
new_u_:{[v;h;a]
   num:(#a)_/:v@&(,0)~/:_ss[;a]'v
   v:@[num;_n;{r:@[0$;x;:]; :[*r;0;r 1]}]
  `$a,${[v;h;a;x]:[x _in v;1;.u.symbol_hash16[`$a,$x]_in h]}[v;h;a](1+)/1 }
tab_u:{
  Axes.tab..j.tab }
idx_u:{[u]
  :[#s:Axes.tab[~u;`j;`s]
    ?s[;1]
    s ] }
var_u:{[u]
  `$".k.Axes.tab.",$u }
rep_u:{[u;i;j;k]
  Axes.tab[u;;i]:Axes.tab[u;;j]					/ new positions i for old positions j
  Axes.hash[u;i]:Axes.hash[u;j]					/ new positions i for old positions j for hash
  Axes.tab[~u;`j;`s]:1,'k					/ new selection k
  active_u[]
  }
up_u:{
  if[#u:tab_u[]							/ if a tab is selected
    if[#i:idx_u u						/ and there is a selection in that tab
      if[~0>j:-1+*i						/ and the first item in the selection isn't the first item
        rep_u[u;j,i;i,j;i-1] ] ] ]				/ then do the move up
  }
down_u:{
  if[#u:tab_u[]							/ if a tab is selected
    if[#i:idx_u u						/ and there is a selection in that tab
      if[(#Axes.tab[u;0])>j:1+*|i				/ and the last item in the selection isn't the last item
        rep_u[u;i,j;j,i;i+1]]]] }				/ then do the move down
top_u:{
  if[#u:tab_u[]							/ if a tab is selected
    if[#i:idx_u u						/ and there is a selection in that tab
      rep_u[u;_n;i,j:(!#Axes.tab[u;0])_dvl i;!#i]]]		/ then move the selection to the top
  }
bottom_u:{
  if[#u:tab_u[]							/ if a tab is selected
    if[#i:idx_u u						/ and there is a selection in that tab
      rep_u[u;_n;(j:n _dvl i),i;(-#i)#n:!#Axes.tab[u;0]]]]	/ then move the selection to the bottom
  }
sort_u:{
  if[#u:tab_u[]							/ if a tab is selected
    j:<. (var_u u),1						/ j is new permutation
    if[~j~i:!#j							/ if it is in fact a new ordering
      rep_u[u;i;j;()] ] ]
  }
cancel_u:{
  .j.d`.k.Axes
  }
diff:{[uu]
  u:.G`axes
  d:(!u)@&~u[]~'uu@!u
  ,/diff_'[d;u d;uu d] }
diff_:{[d;u;uu]
  a:(!uu)@&~(!uu)_lin!u
  b:(!u)@&~(!u)_lin!uu
  {d,`Append,x}'[a],{d,`Delete,x}'b}
ok_u:{
  .j.stop'.j.w[]
  close_v[]
  xeq_u[();Axes.tab;Axes.hash]
  cancel_u[]
  .j.go'.j.w[]
  }
valid_u:{
  .j.stop'.j.w[]
  close_v[]
  xeq_u[();Axes.tab;Axes.hash]
  cancel_u[]
  valid[]
  }
xeq_u:{[i;tab;hash]
  .k.set_s'[.V..Hash_Location,/:!tab;{.+(x;y)}'[tab[;1];hash[!tab]]]
  dral:{[axis;old;new;log]r:()
    if[~#log;:r]
    d:.+(`old`new;(.+(old;old);.()))
    find:{[d;v]:[v _in d.old[];`old,(!d.old)@d.old[]?v;`new,(!d.new)@d.new[]?v]}	/ location of v in d
    while[#log
      action:*l:*log; log:1_ log							/ setup
      if[`Delete~action;	where:find[d;l 1]; d:@[d;*where;_di;where 1]]		/ delete removes item from dictionary
      if[`Rename~action;	where:find[d;*l 1]; d:.[d;where;:;l[1;1]]]		/ rename changes value in dictionary
      if[`Insert~action;	d:.[d;(`new;l[1;0]);:;l[1;0]]]				/ insert adds to new dictionary
      if[`Append~action;	d:.[d;(`new;l 1);:;l 1]]				/ append adds to new dictionary
      ]
    if[#deleted:old _dvl !d.old;		r,:,(axis;`D;deleted)]
    if[#renamed:(!d.old)@&~(!d.old)=d.old[];	r,:,(axis;`R;d.old)]
    if[#added:d.new[];				r,:,(axis;`A;added)]
    if[(#deleted,renamed,added)|~old~new;	r,:,(axis;`L;new)]
    r}
  xeq_u_[i;list:,/dral'[!tab;!:'.G[`axes;!tab];tab[;1];tab[.;`Log]];tab;1]
  }
xeq_u_:{[i;list;tab;update_editor]
  if[#list
    set_s[i;(SS:,init_I[*SS:Axis.Apply[i]/[.[,.();i;:;get_s i];list;tab@list[;0]]]) . i]
    reset_ref[list]
    ]
  SS:_n
  set_U[tab]
  if[update_editor
    i:selected[]
    reset_def subpath_i i
    log.set[i;-1;(`action`flexible_axes;`axes,,list)]
    ]
  status"Flexible axes modified"
  }
reset_ref:{[list]
  n:0,'.u.treepaths get_s 0
  j:&~_n~'r:{get_s attr[x],`R}'n;r@:j;n@:j
  reset_ref_[r;n]'list
  }
reset_ref_:{[r;n;list] / r:references; n:nodes for references; list:flexible axis adjustment
  if[`D~list 1
    status("Removing references to elements deleted from flexible axis &0";_ssr[$*list;"_";" "])
    j:&{|/{x~(#x)#y}[;y]'x}[,/.V..A[*list],\:/:list 2]'r
    {set_s[attr[x],`R;_n]}'n j
    ]
  if[`R~list 1
    status("Changing references for elements renamed in flexible axis &0";_ssr[$*list;"_";" "])
    change:{((!x)@i;(x[])@i:&~(!x)=x[])}[list 2]
    j:&:'r{|/{x~(#x)#y}[;y]'x,\:z}[.V..A[*list]]\:/:*change
    {set_s[attr[x],`R;y]}''[n j;{:[y _in *x;x[1;x[0]?y];y]}[change]'''r j]
    ]
  }
subpath_i:{[i]
  j:1
  do[#i:add i
    if[_n~get_s j#i
      :(j-1)#i ]
    j+:1 ]
  i}
set_U:{[tab]
  set_u'[!tab;tab[]]
  }
set_u:{[u;d]
  .G[`axes;u]:.+|d}

new_element_tree:{[i]
 .j.stop'.j.w[]
 u:get_s attr[i],`U
 new:new_u_[$!.G[`axes;u];(.k.get_s .V..Hash_Location,u)[];($u),"_"]
 list:((u;`A;,new);(u;`L;(!.G[`axes;u]),new))
 xeq_u_[0,`A;list;.,(u;(.G[`axes;u;],1;(!.G[`axes;u]),new));1]
 set_s[.V..Hash_Location,u,new;.u.symbol_hash16@new]
 .j.go'.j.w[]
 }
rename_element_tree:{[i]
 .j.stop'.j.w[]
 u:get_s attr[-1_ i],`U
 new:.j.Input[old:*|i;`"New: ";`"Rename Element"]
 if[~old~new:u_u_[u;a:!.G[`axes;u];old;new]				/ a:old axis labels
   tab:.,(u;(.G[`axes;u;];n:@[a;&old=a;:;new]))			/ n:new axis labels
   log:((u;`R;.+(a;n));(u;`L;n))
   Main.split[`left;`folders;`tree.;`j;`s]:,sub (-1_ i),new
   xeq_u_[0,`A;log;tab;1]
   set_s[.V..Hash_Location,u;.+@[+. get_s@.V..Hash_Location,u;0;{[old;new;x]@[x;&old=x;:;new]}[old;new]]]
   ]
 .j.go'.j.w[]
 }
delete_element_tree:{[i]
 .j.stop'.j.w[]
 list:{(!x)@&x[]}@.G[`axes;u:get_s attr[-1_ i],`U]
 tab:.,(u;|2#+..G[`axes;u] _di del:*|i)
 log:((u;`D;,del);(u;`L;list _dv del))
 Main.split[`left;`folders;`tree.;`j;`s]:,sub (-1_ i),:[0~w:list?del;*1_ list;list@w-1]
 xeq_u_[0,`A;log;tab;1]
 set_s[.V..Hash_Location,u;get_s[.V..Hash_Location,u]_di del]
 .j.go'.j.w[]
 }
deactivate_element_tree:{[i]
 .j.stop'.j.w[]
 list:{(!x)@&x[]}@.G[`axes;u:get_s attr[-1_ i],`U]
 tab:.,(u;|2#+.@[.G[`axes;u];dea:*|i;:;0])
 Main.split[`left;`folders;`tree.;`j;`s]:,sub (-1_ i),:[0~w:list?dea;*1_ list;list@w-1]
 xeq_u_[0,`A;();tab;1]
 .j.go'.j.w[]
 }

Axis.Apply:{[i;s;list;tab]
 / i: list restrictor (used to determine at which point to start expanding)
 / s: data source (.S)
 / list: triple (flexible axis;action;items)
 / tab:
 status("Modifying flexible axis &0. Action: &1";_ssr[$*list;"_";" "];$(.+(`C`D`R`A`L;`Create`Delete`Rename`Append`List))@list 1)
 set_u[*list;tab]
 alist:()
 if[(*list) _in !.V..A
   alist:{y@&{x~(#x)#y}[x]'y}[i;.k.Axis.expand[s;i;.V..A[*list]]]
   if[`A~list 1; list[2]:(list 2;.V..A[*list])]
   s:.k.Axis.A[list 1][;;list 2]/[s;alist]
   if[`A~list 1; list[2]:*list 2]
   ]
 if[(*list) _in !.V..J
   jlist:{y@&{x~(#x)#y}[x]'y}[i;.k.Axis.expand[s;i;.V..J[*list]]]
   s:.k.Axis.J[;;list]/[s;jlist]
   ]
 if[`R ~ list 1
   paths:0,/:{l@&`N _in/:!:'x .'attr'l:.u.treepaths x}@.N 0
   rename:{[a;r;p]i:&a~'(#:'a)#\:p
    :[~#i;p
      (p@c:#a@*i) _in !r; @[p;c;:;r@p@c]
      p]}
   new:rename[alist;list 2]'paths
   update_links:{[a;r;n]
     if[#i:_ss[.u.lc n;"href=\"self://"]
       user:{x:_ssr[13_ x;"/";"\\"]; x:(x?"\"")#x; x}'i _ n
       nn:(0,,/+(i+13;i+13+#:'user)) _ n
       paths:0,/:labels_to_path'`$.u.cut["\\"]'user
       new:sub'rename[a;r]'add'paths
       if[#i:&~paths~'new
         labels:{[o;n]r:{1_,/"\\",/:x}@$path_to_labels@1_ n;r:_ssr[r;"..";_ssr[$*n@&~o~'n;"_";" "]];r}'[paths i;new i]
         n:,/@[nn;1+2*i;:;labels]
         ]
       ]
     n}
   i:&~paths~'new							/ find places where notes location has changed
   .N:./[.N;-1_'paths i;{[x;y].+(@[!y;i;:;x@(!y)@i:&(!y) _lin !x];y[];y[.])}[list 2]]					/ add notes in new locations
   .N:./[.N;(attr'new),\:`N;update_links[alist;list 2]]			/ update internal links
   ]
 s}

Axis.expand:{[s;i;list]
 list:list@&{&/{y _in _n,`,x}'[x;y]}[i]'(#i)#/:list
 {(&0~/:x) _ x}@,//Axis.expand_[s]'i,/:(#i)_/:list}		/ expand each, splitting at zeros(?)
Axis.expand_:{[s;list]r::[_n _in list; _f[s]'root,/:(!s . root:i#list),\:(1+i:list?_n)_ list; ,list];,/r}	/ expand sources at flexible axis points
Axis.V_equiv:{[w;list]							/ w:particular instance; list:list of .V locations with nulls
  w:{[x;y]y@*&{:[(#x)~#y;&/{:[x~y;1;y~_n;1;0]}'[x;y];0]}[x]'y}[w;list]	/ find member in list which matches w, with null tolerance
  while[#i:&_n~/:w; w:@[w;*i;:;*!.V . (*i)#w]]				/ replace nulls with valid path into .V
  w}
Axis.A.C:{[s;w;i]
 ul:(ui:*&"_1"~/:-2#'$u)#u:!s . w; uu:u@ui; ur:(ui+1)_ u
 ww:w,/:(ul,((#i)#uu),ur)
 .[s;w;:;.+(ul,i,ur;s ./:ww;s ./:attr' ww)]}
Axis.A.D:{[s;w;i].[s;w;_di[;i]]}
Axis.A.R:{[s;w;i].[s;w;{.+(x[];y@!x;y@~!x)}[i]]}
Axis.A.A:{[s;w;i]
 wvv:wv,element:*!.V . wv:Axis.V_equiv[w;i 1]
 vd:(init_u[wvv;.[,.();wv;:;.,(element;.V . wvv;.V . attr wvv)]]) . wvv
 r:1_ init_i . (`;vd;.V . attr wvv)
 s:.[s;w;{[w;d;e;x]x:@[x;w;:;d];@[x;~w;:;e]}[*i;r 0;r 1]]
 s}
Axis.A.L:{[s;w;i]
 if[(#i)<#!s . w
   u:s . (attr w),`U
   f:{:[6=4:x;0#`;(),x]}
   i:f[.V..Leading@u],i,f[.V..Trailing@u]
   i@:&i _lin !s . w
   ]
 .[s;w;{.+(x;y@x;y@~x)}[i]]}
Axis.J:{[s;w;list]
 axis:list 0; action:list 1; args:list 2
 if[5=4:J:s . (wa:attr w),`J
   if[axis _in !J; J:J@axis]
   s:./[s;(w;wa);:;J[action][s . w;s . wa;axis;args]]
   ]
 s}

Axes..j.f1:{}

Axes..j.menu.File.OK:ok_u
Axes..j.menu.File.Cancel:cancel_u

Axes..j.menu.Edit.Append:append_u
Axes..j.menu.Edit.Append_Multiple_:append_multiple_u
Axes..j.menu.Edit.Insert:insert_u
Axes..j.menu.Edit.Delete:delete_u

Axes..j.menu.Order.Top:top_u
Axes..j.menu.Order.Up:up_u
Axes..j.menu.Order.Down:down_u
Axes..j.menu.Order.Bottom:bottom_u
Axes..j.menu.Order.s0:" "
Axes..j.menu.Order.Sort:sort_u

Axes..j.menu.Select.All:all_u
Axes..j.menu.Select.With:with_u
Axes..j.menu.Select.Without:without_u
Axes..j.menu.Select.Only:only_u
Axes..j.menu.Select.Except:except_u

Axes..j.menu.Help[.a[`APP_Help]]:{}
Axes..j.menu.Help.Definition_Editor_Help:{}
Axes..j.menu.Help.Flexible_Axes_Help:{}
Axes..j.menu.Help.s0:" "
Axes..j.menu.Help[.a[`About_APP]]:{}

Axes..j.menu..j.ne:++({p:.u.treepaths x;p@&(4::'x .'p)_lin 5 7}@Axes..j.menu;1)

Axes..j.menu..j.mnem:+((,`File				;`f)
                       (`File`OK			;`o)
                       (`File`Cancel			;`c)
                       (,`Edit				;`e)
                       (`Edit`Append			;`a)
                       (`Edit`Insert			;`i)
                       (`Edit`Append_Multiple_		;`m)
                       (`Edit`Delete			;`d)
                       (,`Order				;`o)
                       (`Order`Top			;`t)
                       (`Order`Up			;`u)
                       (`Order`Down			;`d)
                       (`Order`Bottom			;`b)
                       (`Order`Sort			;`s)
                       (,`Select			;`s)
                       (`Select`All			;`a)
                       (`Select`With			;`w)
                       (`Select`Without			;`t)
                       (`Select`Only			;`o)
                       (`Select`Except			;`e)
                       (,`Help				;`h)
                       (`Help,.a[`APP_Help]		;`h)
                       (`Help`Definition_Editor_Help	;`d)
                       (`Help`Flexible_Axes_Help	;`f)
                       (`Help,.a[`About_APP]		;`a))

Axes..j.menu..j.async:2

Axes.buttons.OK:ok_u
/ Axes.buttons.Valid:valid_u
Axes.buttons.Cancel:cancel_u
Axes.buttons.OK..j.async:2

/ Hack fix for buttons not being placed correctly
/Axes.buttons.OK..j.insets: 6 6 6 3
/Axes.buttons.Cancel..j.insets: 6 6 3 6

/Axes.buttons.Valid..j.async:2
Axes.tab:.()
Axes.tab..j.tabs:`l
Axes.tab..j.scroll:1
Axes.tab..j.wy:1.
Axes.tab..j.wx:1.
Axes.tab..j.tab..j.t:active_u

Axes.toolbar..j.border:0
Axes.toolbar..j.dir:`v
Axes.toolbar..j.wx:.j.NoExtraSpace
Axes.toolbar..j.floatable:1
Axes.toolbar..j.l:"Axes"
Axes.toolbar..j.a:`Text`Append`Insert`Delete``Top`Up`Down`Bottom`Sort``All`With`Without`Only`Except

text_on:{
 b:(!`.-1_.j.v)_dv`Text
 j:(-1_.j.v),(,~b),`j
 .[`;j,`l;:;b]
 }

text_off:{
 b:(!`.-1_.j.v)_dv`Text
 j:(-1_.j.v),(,~b),`j
 .[`;j,`l;:[;""]]
 }

Axes.toolbar.Text:0
Axes.toolbar.Text..j.c:`togglebutton
Axes.toolbar.Text..j.l:`"<html><center>Button<br>Labels</center></html>"
Axes.toolbar.Text..j.help:"Annotate buttons with text"
Axes.toolbar.Text..j.t:{:[`..j.v;text_on[];text_off[]]}

Axes.toolbar.Append:append_u
Axes.toolbar.Append_Multiple:append_multiple_u
Axes.toolbar.Insert:insert_u
Axes.toolbar.Delete:delete_u
Axes.toolbar[~`Append`Append_Multiple`Insert`Delete;`j;`c]:`button
Axes.toolbar[~`Append`Append_Multiple`Insert`Delete;`j;`l]:4#,""
Axes.toolbar[~`Append`Append_Multiple`Insert`Delete;`j;`image]:("Append_32.png";"Append_Multiple.png";"Insert_32.png";"Delete_32.png")
Axes.toolbar[~`Append`Append_Multiple`Insert`Delete;`j;`help]:("Append new axis element";"Append multiple new axis elements";"Insert new axis elements above selected element(s)";"Delete selected axis element(s)")
Axes.toolbar[~`Append`Append_Multiple`Insert`Delete;`j;`hpos]:`r
Axes.toolbar[~`Append`Append_Multiple`Insert`Delete;`j;`vpos]:`c

Axes.toolbar.Top:top_u
Axes.toolbar.Up:up_u
Axes.toolbar.Down:down_u
Axes.toolbar.Bottom:bottom_u
Axes.toolbar.Sort:sort_u
Axes.toolbar[~`Top`Up`Down`Bottom`Sort;`j;`c]:`button
Axes.toolbar[~`Top`Up`Down`Bottom`Sort;`j;`l]:5#,""
Axes.toolbar[~`Top`Up`Down`Bottom`Sort;`j;`image]:("Move_Top_32.png";"Move_Up_32.png";"Move_Down_32.png";"Move_Bottom_32.png";"Sort_32.png")
Axes.toolbar[~`Top`Up`Down`Bottom`Sort;`j;`help]:("Move selected axis element(s) to the top";"Move selected axis element(s) up";"Move selected axis element(s) down";"Move selected axis element(s) to the bottom";"Put axis elements in alphabetic sort order")
Axes.toolbar[~`Top`Up`Down`Bottom`Sort;`j;`hpos]:`r
Axes.toolbar[~`Top`Up`Down`Bottom`Sort;`j;`vpos]:`c

Axes.toolbar.All:all_u
Axes.toolbar.With:with_u
Axes.toolbar.Without:without_u
Axes.toolbar.Only:only_u
Axes.toolbar.Except:except_u
Axes.toolbar[~`All`With`Without`Only`Except;`j;`c]:`button
Axes.toolbar[~`All`With`Without`Only`Except;`j;`l]:5#,""
Axes.toolbar[~`All`With`Without`Only`Except;`j;`image]:("Check_All_32.png";"Check_With_32.png";"Check_Without_32.png";"Check_Only_32.png";"Check_Except_32.png")
Axes.toolbar[~`All`With`Without`Only`Except;`j;`help]:("Turn on all axis element(s)";"Turn on selected axis element(s)";"Turn off selected axis element(s)";"Turn on selected axis element(s) and turn off others";"Turn off selected axis element(s) and turn on others")
Axes.toolbar[~`All`With`Without`Only`Except;`j;`hpos]:`r
Axes.toolbar[~`All`With`Without`Only`Except;`j;`vpos]:`c

Axes.buttons..j.c:`panel
Axes.buttons..j.border:0
Axes.buttons..j.wy:.j.NoExtraSpace
Axes.buttons..j.a:,`OK`Cancel
Axes.buttons[~`OK`Valid`Cancel;`j;`c]:`button
Axes.buttons[~`OK`Valid`Cancel;`j;`l]:(,"";,"";,"")
Axes.buttons[~`OK`Valid`Cancel;`j;`image]:("OK.png";"Validate.png";"Cancel.png")
Axes.buttons[~`OK`Valid`Cancel;`j;`fill]:`h

Axes..j.a:(`tab`toolbar;`buttons)
Axes..j.c:`panel
Axes..j.l:`"Edit Flexible Axes"
Axes..j.xy:(.+(`w`m`j;(902 703;948 869;958 699)))[.p.Look_and_Feel]
Axes..j.close:cancel_u
Axes..j.modal:1
Axes..j.on:`.k.Main

get_s:{[i]`.S . i}

axes:{create_u@!.G`axes}
.j.Java {
  axes[]
}
Axes..j.z: {
 if[1~.k[`autoExit]; _exit 0]
}