kModule: (.((`B
    .((`GEMS
       {[x;junk]act[x;.j.v]}[`GEMS]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`scrollbarblue;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Economic_Variables
       {[x;junk]act[x;.j.v]}[`Economic_Variables]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`scrollbarblue;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Financial_Markets
       {[x;junk]act[x;.j.v]}[`Financial_Markets]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`User_Paths
       {[x;junk]act[x;.j.v]}[`User_Paths]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Inner_Loop_Projections
       {[x;junk]act[x;.j.v]}[`Inner_Loop_Projections]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`User_Values
       {[x;junk]act[x;.j.v]}[`User_Values]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Property_Casualty
       {[x;junk]act[x;.j.v]}[`Property_Casualty]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Business_Modeled
       {[x;junk]act[x;.j.v]}[`Business_Modeled]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Prior_Accident_Periods
       {[x;junk]act[x;.j.v]}[`Prior_Accident_Periods]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Starting_Unearned
       {[x;junk]act[x;.j.v]}[`Starting_Unearned]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Future_Written
       {[x;junk]act[x;.j.v]}[`Future_Written]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Acquisition_Costs
       {[x;junk]act[x;.j.v]}[`Acquisition_Costs]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Underwriting_Expenses
       {[x;junk]act[x;.j.v]}[`Underwriting_Expenses]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Commissions_and_Brokerage
       {[x;junk]act[x;.j.v]}[`Commissions_and_Brokerage]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Taxes_Licenses_and_Fees
       {[x;junk]act[x;.j.v]}[`Taxes_Licenses_and_Fees]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Contingent_Commissions
       {[x;junk]act[x;.j.v]}[`Contingent_Commissions]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Management_Fees
       {[x;junk]act[x;.j.v]}[`Management_Fees]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Loss_Adjustment_Expenses
       {[x;junk]act[x;.j.v]}[`Loss_Adjustment_Expenses]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Allocated
       {[x;junk]act[x;.j.v]}[`Allocated]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Unallocated
       {[x;junk]act[x;.j.v]}[`Unallocated]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Salvage_and_Subrogation
       {[x;junk]act[x;.j.v]}[`Salvage_and_Subrogation]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Policyholder_Dividends
       {[x;junk]act[x;.j.v]}[`Policyholder_Dividends]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Reinsurance
       {[x;junk]act[x;.j.v]}[`Reinsurance]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Reserves
       {[x;junk]act[x;.j.v]}[`Reserves]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Life_Insurance
       {[x;junk]act[x;.j.v]}[`Life_Insurance]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Investments
       {[x;junk]act[x;.j.v]}[`Investments]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Financing
       {[x;junk]act[x;.j.v]}[`Financing]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Supplemental_Models
       {[x;junk]act[x;.j.v]}[`Supplemental_Models]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Accounting
       {[x;junk]act[x;.j.v]}[`Accounting]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Economic
       {[x;junk]act[x;.j.v]}[`Economic]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Solvency_II
       {[x;junk]act[x;.j.v]}[`Solvency_II]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`IFRS
       {[x;junk]act[x;.j.v]}[`IFRS]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`US_GAAP
       {[x;junk]act[x;.j.v]}[`US_GAAP]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`US_Statutory
       {[x;junk]act[x;.j.v]}[`US_Statutory]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`US_Statutory_Life
       {[x;junk]act[x;.j.v]}[`US_Statutory_Life]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`HGB
       {[x;junk]act[x;.j.v]}[`HGB]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`HGB_Life
       {[x;junk]act[x;.j.v]}[`HGB_Life]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Consolidation
       {[x;junk]act[x;.j.v]}[`Consolidation]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Tax
       {[x;junk]act[x;.j.v]}[`Tax]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Regulatory
       {[x;junk]act[x;.j.v]}[`Regulatory]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`NAIC_Risk_Based_Capital
       {[x;junk]act[x;.j.v]}[`NAIC_Risk_Based_Capital]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`NAIC_Risk_Based_Capital_Life
       {[x;junk]act[x;.j.v]}[`NAIC_Risk_Based_Capital_Life]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Standard_and_Poors
       {[x;junk]act[x;.j.v]}[`Standard_and_Poors]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Standard_and_Poors_Life
       {[x;junk]act[x;.j.v]}[`Standard_and_Poors_Life]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`AM_Best
       {[x;junk]act[x;.j.v]}[`AM_Best]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`AM_Best_Life
       {[x;junk]act[x;.j.v]}[`AM_Best_Life]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`EU_Solvency_I
       {[x;junk]act[x;.j.v]}[`EU_Solvency_I]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`QIS4
       {[x;junk]act[x;.j.v]}[`QIS4]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`QIS5
       {[x;junk]act[x;.j.v]}[`QIS5]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`BaFin
       {[x;junk]act[x;.j.v]}[`BaFin]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Regulatory_Consolidation
       {[x;junk]act[x;.j.v]}[`Regulatory_Consolidation]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          ))
      (`Developer
       {[x;junk]act[x;.j.v]}[`Developer]
       .,(`j
          .((`c;`button;)
            (`fill;`b;)
            (`bg;`e;)
            (`halign;`l;)
            (`valign;`c;)
            (`lfont;`"Ariel 0 12";))
          )))
    .,(`j
       .((`a
          (`GEMS `Economic_Variables `Economic_Variables
           `GEMS `Financial_Markets `Financial_Markets
           `User_Paths `User_Paths `User_Paths
           `Inner_Loop_Projections `Inner_Loop_Projections `Inner_Loop_Projections
           `User_Values `User_Values `User_Values
           `Property_Casualty `Business_Modeled `Prior_Accident_Periods
           `Property_Casualty `Business_Modeled `Starting_Unearned
           `Property_Casualty `Business_Modeled `Future_Written
           `Property_Casualty `Acquisition_Costs `Underwriting_Expenses
           `Property_Casualty `Acquisition_Costs `Commissions_and_Brokerage
           `Property_Casualty `Acquisition_Costs `Taxes_Licenses_and_Fees
           `Property_Casualty `Acquisition_Costs `Contingent_Commissions
           `Property_Casualty `Acquisition_Costs `Management_Fees
           `Property_Casualty `Loss_Adjustment_Expenses `Allocated
           `Property_Casualty `Loss_Adjustment_Expenses `Unallocated
           `Property_Casualty `Salvage_and_Subrogation `Salvage_and_Subrogation
           `Property_Casualty `Policyholder_Dividends `Policyholder_Dividends
           `Property_Casualty `Reinsurance `Reinsurance
           `Property_Casualty `Reserves `Reserves
           `Life_Insurance `Life_Insurance `Life_Insurance
           `Investments `Investments `Investments
           `Financing `Financing `Financing
           `Supplemental_Models `Supplemental_Models `Supplemental_Models
           `Accounting `Economic `Economic
           `Accounting `Solvency_II `Solvency_II
           `Accounting `IFRS `IFRS
           `Accounting `US_GAAP `US_GAAP
           `Accounting `US_Statutory `US_Statutory
           `Accounting `US_Statutory_Life `US_Statutory_Life
           `Accounting `HGB `HGB
           `Accounting `HGB_Life `HGB_Life
           `Accounting `Consolidation `Consolidation
           `Tax `Tax `Tax
           `Regulatory `NAIC_Risk_Based_Capital `NAIC_Risk_Based_Capital
           `Regulatory `NAIC_Risk_Based_Capital_Life `NAIC_Risk_Based_Capital_Life
           `Regulatory `Standard_and_Poors `Standard_and_Poors
           `Regulatory `Standard_and_Poors_Life `Standard_and_Poors_Life
           `Regulatory `AM_Best `AM_Best
           `Regulatory `AM_Best_Life `AM_Best_Life
           `Regulatory `EU_Solvency_I `EU_Solvency_I
           `Regulatory `QIS4 `QIS4
           `Regulatory `QIS5 `QIS5
           `Regulatory `BaFin `BaFin
           `Regulatory `Regulatory_Consolidation `Regulatory_Consolidation
           `Developer `Developer `Developer)
          )
         (`c;`window;)
         (`border;0;)
		 (`async;2;))
       ))
   (`controls
    .((`OK
       {
	   :[.j.yesno["Close dialog?"]~`Yes; .j.d`modal]
}
       .,(`j
          .((`image;"OK.png";)
            (`l;"";)
			(`async;1)
            (`fill;`h;))
          ))
      (`Cancel
       {.j.d`modal}
       .,(`j
          .((`image;"Cancel.png";)
            (`l;"";)
            (`fill;`h;))
          ))
      (`Reset
       {Module[`B]:super.reset[Module`B;.G`submodules]}
       .,(`j
          .((`image;"Reset.png";)
            (`l;"";)
            (`fill;`h;))
          ))
      (`Clear
       {Module[`B]:super.reset[Module`B;0#`]}
       .,(`j
          .((`image;"Clear.png";)
            (`l;"";)
            (`fill;`h;))
          )))
    .,(`j
       .((`c;`panel;)
         (`border;0;)
         (`a
          (`OK `Cancel `Reset `Clear
           `OK `Cancel `Reset `Clear)
          )
         (`wy;1e-010;)
         (`async;2;))
       )))
 .((`j
    .((`a
       `B `controls
       )
      (`c;`panel;)
      (`close;{.j.d`.k.Module;.j.go'.j.w[]};)
      (`l;`"Module Selection";)
      (`modal;1;)
      (`xy
       720 932
       .())
      (`f1;{help.o `DefinitionEditor_ModuleSelection.html};)
      (`on;`.k.Main;)
      (`loc
       574 0
       .()))
    .,(`t;".j.k[];.j.flush[];";))
   (`t;".j.k[];.j.flush[];";)))


p: .()
p..j.c: `panel
p..j.l: "Module Selection (Modal)"

p.button:{_n
			.j.c`modal
			modal..j.loc::300 50
			modal..j.xy::720 932}

p.button..j.async: 1
p.button..j.l: "Show Module Selection Dialog"

modal: .()
modal..j.c:`panel
modal..j.modal:1
modal..j.ontop:0

modal.Module: kModule[0]
modal.Module.: kModule[1]

modal..j.close: {:[.j.yesno["Close dialog?"]~`Yes; .j.d`modal]}

.j.Java {
  .j.c`p
}
p..j.z: {
 if[1~.k[`autoExit]; _exit 0]
}
