var simulation = {
    "_id" : ObjectId("60c0bb59d6441c0008f33f46"),
    "name" : "sims/LMAssetOnlySim",
    "jobIds" : [
        "Simulation_rasjoh_rashainejoh1c30___40007_2021_06_09_08_59_45"
    ],
    "scenarios" : NumberInt(100),
    "status" : "Complete",
    "gridName" : "default",
    "dfsPath" : "sims/LMAssetOnlySim.dfs",
    "version" : "0.1",
    "productVersion" : "7.3.1.0",
    "billingInformation" : {
        "startTime" : NumberInt(1623243612),
        "simulationWorkerEndTime" : NumberInt(1623244093),
        "compilationEndTime" : NumberInt(1623243715),
        "provisionedElements" : NumberInt(1875000000),
        "elements" : NumberInt(29054366)
    },
    "createdBy" : "auth0|5e8de1b95234db0beb4a692a",
    "modifiedBy" : "auth0|5e8de1b95234db0beb4a692a",
    "createdTime" : ISODate("2021-06-09T13:00:09.964+0000"),
    "modifiedTime" : ISODate("2021-06-09T13:08:13.086+0000"),
    "deletedTime" : null,
    "path" : "s3://stackset-advise-869dfbb0-6f22-49-simulationbucket-vy6opah7khel/60c0bb59d6441c0008f33f46",
    "archived" : false,
    "axes" : [
        "Asset_Class",
        "Base",
        "Bond_Market",
        "Component",
        "Compounding",
        "Constraint",
        "Constraint_Type",
        "Coupon",
        "Coupon_Frequency",
        "Currency",
        "Decision_Submodule",
        "Derivative_Market",
        "Direction",
        "Economic_Variable",
        "Economy",
        "Entity",
        "FTime",
        "Field",
        "Frequency",
        "Grouping",
        "Item",
        "Market",
        "Market_Index",
        "Maturity",
        "Measure",
        "Method",
        "Module",
        "Mortgage_Market",
        "Original_Currency",
        "Portfolio",
        "Previous_Rating",
        "Price_Index",
        "Projection",
        "Property_Market",
        "Quote",
        "Rating",
        "Reference",
        "Reference_Module",
        "Return_Class",
        "Sector",
        "Simulation",
        "Source",
        "Standard",
        "Statement",
        "Statement_Line",
        "Status",
        "Stock_Index",
        "Tax_Rates",
        "Tenor_Density",
        "Time_Frame",
        "Timing",
        "Transaction",
        "User_Value",
        "Security",
        "Taxlot",
        "Year",
        "Scenario"
    ],
    "economies" : [
        "US"
    ],
    "elements" : "29054366",
    "frequencies" : [
        "Year"
    ],
    "modules" : [
        "Accounting",
        "Decision",
        "Economies",
        "Entities",
        "Holdings",
        "Markets",
        "Portfolios",
        "Returns",
        "Securities",
        "Tax",
        "User_Values"
    ],
    "periods" : {
        "year" : NumberInt(6)
    },
    "size" : "70135533",
    "variables" : NumberInt(10279)
}

db.simulations.insert(simulation);


