legend: (.((`t
    .()
    .,(`j
       .((`c;`panel;)
         (`border;0;)
         (`bg;255255255;)
         (`wy;0.5;))
       ))
   (`a
    0
    .,(`j
       .((`c;`check;)
         (`l;`"All Active";)
         (`lbg;255255255;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    e:Output[`tab;`Asset_Allocation_Chart;`Label;~ACF;`j;`e]
    Output[`tab;`Asset_Allocation_Chart;`Label;ACF]:e*`. .j.v
    set_allocation_annotation[]
    };))
       ))
   (`a0
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp A 00 05";)
         (`lbg;255255000;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };)
         (`fill;`h;))
       ))
   (`a1
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp A 05 10";)
         (`lbg;215185000;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a2
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp A 10 20";)
         (`lbg;160090000;)
         (`lfg;255255255;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a3
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp A 20 up";)
         (`lbg;220220220;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a4
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp BBB 00 05";)
         (`lbg;255210;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a5
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp BBB 05 10";)
         (`lbg;215121;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a6
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp BBB 10 20";)
         (`lbg;160000;)
         (`lfg;255255255;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a7
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp BBB 20 up";)
         (`lbg;165165165;)
         (`lfg;255255255;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a8
    0
    .,(`j
       .((`c;`check;)
         (`l;`"US Stock";)
         (`lbg;90090090;)
         (`lfg;255255255;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`b
    .()
    .,(`j
       .((`c;`panel;)
         (`border;0;)
         (`bg;255255255;)
         (`wy;0.5;))
       )))
 .((`t
    .()
    .,(`j
       .((`c;`panel;)
         (`border;0;)
         (`bg;255255255;)
         (`wy;0.5;))
       ))
   (`a
    0
    .,(`j
       .((`c;`check;)
         (`l;`"All Active";)
         (`lbg;255255255;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    e:Output[`tab;`Asset_Allocation_Chart;`Label;~ACF;`j;`e]
    Output[`tab;`Asset_Allocation_Chart;`Label;ACF]:e*`. .j.v
    set_allocation_annotation[]
    };))
       ))
   (`a0
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp A 00 05";)
         (`lbg;255255000;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };)
         (`fill;`h;))
       ))
   (`a1
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp A 05 10";)
         (`lbg;215185000;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a2
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp A 10 20";)
         (`lbg;160090000;)
         (`lfg;255255255;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a3
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp A 20 up";)
         (`lbg;220220220;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a4
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp BBB 00 05";)
         (`lbg;255210;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a5
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp BBB 05 10";)
         (`lbg;215121;)
         (`lfg;0;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a6
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp BBB 10 20";)
         (`lbg;160000;)
         (`lfg;255255255;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a7
    0
    .,(`j
       .((`c;`check;)
         (`l;`"Bonds Corp BBB 20 up";)
         (`lbg;165165165;)
         (`lfg;255255255;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`a8
    0
    .,(`j
       .((`c;`check;)
         (`l;`"US Stock";)
         (`lbg;90090090;)
         (`lfg;255255255;)
         (`wy;1e-010;)
         (`e;0;)
         (`t;{
    set_allocation_annotation[]
    };))
       ))
   (`b
    .()
    .,(`j
       .((`c;`panel;)
         (`border;0;)
         (`bg;255255255;)
         (`wy;0.5;))
       ))))


p: legend[0]
p.: legend[1]
p..j.c:`panel
p..j.l: "EFA Legend"


/p.internalPanel..j.c: `panel
/p.internalPanel..j.border:0
/p.internalPanel..j.anchor:`c
/p.internalPanel..j.fill:`h

p..j.close:{_exit 0}
.j.Java{
  .j.c `p
};
p..j.z: {
  if[1~.k[`autoExit];_exit 0]
  }