/ Copyright (c) 2012 Conning Services (Ireland) Limited
/ Josef Sachs

/ font utility

\l main/j/j

.j.Java{
 .k.Font.font:.j.FONT_FAMILIES
 .k.Font.example:(#Font`font)#`$32__ci!256
 .k.Font..j.font.example:`$($Font`font),\:" 0 18"
 .k.Font..j.h:25
 .k.Font..j.xy:1400 750
 .k.Font..j.close:{_exit 0}
 .j.c`.k.Font
};

\
second word of font entry is 0 (normal), 1 (bold), 2 (italic), 3 (bold italic)
third word of font entry is integer point size
