asd:((0.25 0.55 0.2
  0.08 0.01 0.1 0.06 0.01 0.07 0.05 0.02 0.27 0.13 0.2)
 .,(`j
    .((`c;`hcpie;)
      (`title;"Asset Allocation Pie Chart: Inefficient Point 110";)
      (`subtitle;"Click an Asset Class Group to drill down. Click again to return.";)
      (`labels
       (("Bonds Corp A"
         "Government"
         "US Stock")
        ("Bonds Corp A 00 05"
         "Bonds Corp A 05 10"
         "Bonds Corp A 10 20"
         "Bonds Corp A 20 up"
         "Government 00 01"
         "Government 03 05"
         "Government 05 07"
         "Government 07 10"
         "Government 10 20"
         "Government 20 up"
         "US Stock"))
       )
      (`colors
       ((230 77 77
         77 230 77
         77 77 230)
        (245 188 188
         235 112 112
         224 36 36
         156 22 22
         188 245 188
         143 239 143
         99 233 99
         54 226 54
         29 201 29
         22 156 22
         77 77 230))
       )
      (`drill
       .((`values
          (((0.25
             0.08 0.01 0.1 0.06)
            (0.55
             0.01 0.07 0.05 0.02 0.27 0.13)
            (0.2
             ,0.2))
           (((0.25
              0.08 0.01 0.1 0.06)
             (0.25
              0.08 0.01 0.1 0.06)
             (0.25
              0.08 0.01 0.1 0.06)
             (0.25
              0.08 0.01 0.1 0.06))
            ((0.55
              0.01 0.07 0.05 0.02 0.27 0.13)
             (0.55
              0.01 0.07 0.05 0.02 0.27 0.13)
             (0.55
              0.01 0.07 0.05 0.02 0.27 0.13)
             (0.55
              0.01 0.07 0.05 0.02 0.27 0.13)
             (0.55
              0.01 0.07 0.05 0.02 0.27 0.13)
             (0.55
              0.01 0.07 0.05 0.02 0.27 0.13))
            ,(0.2
              ,0.2)))
          )
         (`labels
          ((("Bonds Corp A"
             ("Bonds Corp A 00 05"
              "Bonds Corp A 05 10"
              "Bonds Corp A 10 20"
              "Bonds Corp A 20 up"))
            ("Government"
             ("Government 00 01"
              "Government 03 05"
              "Government 05 07"
              "Government 07 10"
              "Government 10 20"
              "Government 20 up"))
            ("US Stock"
             ,"US Stock"))
           ((("Bonds Corp A"
              ("Bonds Corp A 00 05"
               "Bonds Corp A 05 10"
               "Bonds Corp A 10 20"
               "Bonds Corp A 20 up"))
             ("Bonds Corp A"
              ("Bonds Corp A 00 05"
               "Bonds Corp A 05 10"
               "Bonds Corp A 10 20"
               "Bonds Corp A 20 up"))
             ("Bonds Corp A"
              ("Bonds Corp A 00 05"
               "Bonds Corp A 05 10"
               "Bonds Corp A 10 20"
               "Bonds Corp A 20 up"))
             ("Bonds Corp A"
              ("Bonds Corp A 00 05"
               "Bonds Corp A 05 10"
               "Bonds Corp A 10 20"
               "Bonds Corp A 20 up")))
            (("Government"
              ("Government 00 01"
               "Government 03 05"
               "Government 05 07"
               "Government 07 10"
               "Government 10 20"
               "Government 20 up"))
             ("Government"
              ("Government 00 01"
               "Government 03 05"
               "Government 05 07"
               "Government 07 10"
               "Government 10 20"
               "Government 20 up"))
             ("Government"
              ("Government 00 01"
               "Government 03 05"
               "Government 05 07"
               "Government 07 10"
               "Government 10 20"
               "Government 20 up"))
             ("Government"
              ("Government 00 01"
               "Government 03 05"
               "Government 05 07"
               "Government 07 10"
               "Government 10 20"
               "Government 20 up"))
             ("Government"
              ("Government 00 01"
               "Government 03 05"
               "Government 05 07"
               "Government 07 10"
               "Government 10 20"
               "Government 20 up"))
             ("Government"
              ("Government 00 01"
               "Government 03 05"
               "Government 05 07"
               "Government 07 10"
               "Government 10 20"
               "Government 20 up")))
            ,("US Stock"
              ,"US Stock")))
          )
         (`colors
          (((230 77 77
             (245 188 188
              235 112 112
              224 36 36
              156 22 22))
            (77 230 77
             (188 245 188
              143 239 143
              99 233 99
              54 226 54
              29 201 29
              22 156 22))
            (77 77 230
             ,77 77 230))
           (((230 77 77
              (245 188 188
               235 112 112
               224 36 36
               156 22 22))
             (230 77 77
              (245 188 188
               235 112 112
               224 36 36
               156 22 22))
             (230 77 77
              (245 188 188
               235 112 112
               224 36 36
               156 22 22))
             (230 77 77
              (245 188 188
               235 112 112
               224 36 36
               156 22 22)))
            ((77 230 77
              (188 245 188
               143 239 143
               99 233 99
               54 226 54
               29 201 29
               22 156 22))
             (77 230 77
              (188 245 188
               143 239 143
               99 233 99
               54 226 54
               29 201 29
               22 156 22))
             (77 230 77
              (188 245 188
               143 239 143
               99 233 99
               54 226 54
               29 201 29
               22 156 22))
             (77 230 77
              (188 245 188
               143 239 143
               99 233 99
               54 226 54
               29 201 29
               22 156 22))
             (77 230 77
              (188 245 188
               143 239 143
               99 233 99
               54 226 54
               29 201 29
               22 156 22))
             (77 230 77
              (188 245 188
               143 239 143
               99 233 99
               54 226 54
               29 201 29
               22 156 22)))
            ,(77 77 230
              ,77 77 230)))
          ))
       ))
    ))

p:asd[0]
p.:asd[1]

p..j.l:"Highcharts Pie Chart"


.j.Java{
  .j.c `p
}

p..j.close:{_exit 0}
p..j.z: {
  if[1~.k[`autoExit];_exit 0]
  }