ser:(.((`distress
    .((`metric
       `US_Statutory_Capital_and_Surplus_to_Risk_Based_Capital_Ratio
       .,(`j
          .((`o
             `US_Statutory_Capital_and_Surplus_to_Risk_Based_Capital_Ratio `Standard_and_Poors_AAA_Redundancy_Ratio `Standard_and_Poors_AA_Redundancy_Ratio `Standard_and_Poors_A_Redundancy_Ratio `Standard_and_Poors_BBB_Redundancy_Ratio `AM_Best_Capital_Adequacy_Ratio
             )
            (`ol
             (`US_Statutory_Capital_and_Surplus_to_Risk_Based_Capital_Ratio `Standard_and_Poors_AAA_Redundancy_Ratio `Standard_and_Poors_AA_Redundancy_Ratio `Standard_and_Poors_A_Redundancy_Ratio `Standard_and_Poors_BBB_Redundancy_Ratio `AM_Best_Capital_Adequacy_Ratio
              ("US Statutory Capital and Surplus to Risk Based Capital Ratio"
               "Standard and Poors AAA Redundancy Ratio"
               "Standard and Poors AA Redundancy Ratio"
               "Standard and Poors A Redundancy Ratio"
               "Standard and Poors BBB Redundancy Ratio"
               "AM Best Capital Adequacy Ratio"))
             )
            (`c;`combo;)
            (`l;`Metric;)
            (`anchor;`w;)
            (`wy;0.0;)
            (`fill;`h;)
            (`e;1;)
            (`t;{ .[`;;:;]'[(-1_.j.v),/:(`level;`level.`j`o;`level.`j`ol);(`.(-3_.j.v),`paths.)[`I`O`L;`. .j.v]]};))
          ))
      (`level
       1.0
       .,(`j
          .((`o
             0 0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1 1.05 1.1 1.15 1.2 1.25 1.3 1.35 1.4 1.45 1.5 1.55 1.6 1.65 1.7 1.75 1.8 1.85 1.9 1.95 2 2.05 2.1 2.15 2.2 2.25 2.3 2.35 2.4 2.45 2.5 2.55 2.6 2.65 2.7 2.75 2.8 2.85 2.9 2.95 3 3.05 3.1 3.15 3.2 3.25 3.3 3.35 3.4 3.45 3.5 3.55 3.6 3.65 3.7 3.75 3.8 3.85 3.9 3.95 4 4.05 4.1 4.15 4.2 4.25 4.3 4.35 4.4 4.45 4.5 4.55 4.6 4.65 4.7 4.75 4.8 4.85 4.9 4.95 5
             )
            (`ol
             (0 0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1 1.05 1.1 1.15 1.2 1.25 1.3 1.35 1.4 1.45 1.5 1.55 1.6 1.65 1.7 1.75 1.8 1.85 1.9 1.95 2 2.05 2.1 2.15 2.2 2.25 2.3 2.35 2.4 2.45 2.5 2.55 2.6 2.65 2.7 2.75 2.8 2.85 2.9 2.95 3 3.05 3.1 3.15 3.2 3.25 3.3 3.35 3.4 3.45 3.5 3.55 3.6 3.65 3.7 3.75 3.8 3.85 3.9 3.95 4 4.05 4.1 4.15 4.2 4.25 4.3 4.35 4.4 4.45 4.5 4.55 4.6 4.65 4.7 4.75 4.8 4.85 4.9 4.95 5
              ("0.00"
               "0.05"
               "0.10"
               "0.15"
               "0.20"
               "0.25"
               "0.30"
               "0.35"
               "0.40"
               "0.45"
               "0.50"
               "0.55"
               "0.60"
               "0.65"
               "0.70"
               "0.75"
               "0.80"
               "0.85"
               "0.90"
               "0.95"
               "1.00"
               "1.05"
               "1.10"
               "1.15"
               "1.20"
               "1.25"
               "1.30"
               "1.35"
               "1.40"
               "1.45"
               "1.50"
               "1.55"
               "1.60"
               "1.65"
               "1.70"
               "1.75"
               "1.80"
               "1.85"
               "1.90"
               "1.95"
               "2.00"
               "2.05"
               "2.10"
               "2.15"
               "2.20"
               "2.25"
               "2.30"
               "2.35"
               "2.40"
               "2.45"
               "2.50"
               "2.55"
               "2.60"
               "2.65"
               "2.70"
               "2.75"
               "2.80"
               "2.85"
               "2.90"
               "2.95"
               "3.00"
               "3.05"
               "3.10"
               "3.15"
               "3.20"
               "3.25"
               "3.30"
               "3.35"
               "3.40"
               "3.45"
               "3.50"
               "3.55"
               "3.60"
               "3.65"
               "3.70"
               "3.75"
               "3.80"
               "3.85"
               "3.90"
               "3.95"
               "4.00"
               "4.05"
               "4.10"
               "4.15"
               "4.20"
               "4.25"
               "4.30"
               "4.35"
               "4.40"
               "4.45"
               "4.50"
               "4.55"
               "4.60"
               "4.65"
               "4.70"
               "4.75"
               "4.80"
               "4.85"
               "4.90"
               "4.95"
               "5.00"))
             )
            (`c;`combo;)
            (`l;`Level;)
            (`anchor;`w;)
            (`wy;0.0;)
            (`fill;`h;)
            (`e;1;))
          ))
      (`horizon
       12
       .,(`j
          .((`o
             1 2 3 4 5 6 7 8 9 10 11 12
             )
            (`ol
             (1 2 3 4 5 6 7 8 9 10 11 12
              `"2004Q1" `"2004Q2" `"2004Q3" `"2004Q4" `"2005Q1" `"2005Q2" `"2005Q3" `"2005Q4" `"2006Q1" `"2006Q2" `"2006Q3" `"2006Q4")
             )
            (`c;`combo;)
            (`l;`Horizon;)
            (`anchor;`w;)
            (`wy;0.0;)
            (`fill;`h;)
            (`e;1;))
          ))
      (`panel
       .()
       .,(`j
          .((`c;`panel;)
            (`border;0;)
            (`wy;1.0;))
          )))
    .,(`j
       .((`c;`panel;)
         (`l;`"Definition of Distress";)
         (`anchor;`w;)
         (`wx;0.4;))
       ))
   (`flags
    .((`ALL
       {(`.(-2_.j.v),`paths.`j`Set_)[`All;(-2_.j.v),`paths;_n]}
       .,(`j
          .((`l;`ALL;)
            (`fill;`h;)
            (`c;`button;)
            (`wy;0.0;))
          ))
      (`DISTRESS
       {[x;y;z]
    m:`.(-2_.j.v),`distress`metric
    l:`.(-2_.j.v),`distress`level
    h:`.(-2_.j.v),`distress`horizon
    s:`.(-3_.j.v),`paths.`S,m
    f:`.(-3_.j.v),`paths.`F,m
    H:`.(-3_.j.v),`paths.`H
    e:{[o]
      / e is symbol vector of the selected entities
      / (eventually, this will need to be updated to handle consolidations)
      e::[~_n~t:o`entity_and_accounting_standard; {(!x)@&x[]}{                        x.Entity              }t
          ~_n~t:o`entity_or_portfolio           ; {(!x)@&x[]}{:[x.Display_Entity_Data;x.Entity _di`fill;.()]}t
          ~_n~t:o`treaties_and_products         ; {x.entities@&.j.True=x.entities..j.bg}                     t
                                                  0#` ]
      e }[`.-3_ .j.v]
    if[1<#e;:.j.ok.w .l.ss "More than one entity selected"]
    if[0=#e;:.j.ok.w .l.ss "No entity selected"]
    s[`Entity]:e
    if[(*.m.G[H;(`raxis;s)])~.();:.j.ok.w .l.ss("Distress metric not available for entity &0: &1";e;`.(-2_.j.v),`distress`metric)]
    r:.m.G[H;(`sum_vt;(s;_n;,h))]
    d:r[2;0;0]
    p:&x@f[d;l]
    .[`;(-2_.j.v),y;:;p]
    (`.(-2_.j.v),`paths.`j`Set_)[`Only;(-2_.j.v),`paths;p] }[::;`DISTRESSED]
       .,(`j
          .((`l;`DISTRESS;)
            (`fill;`h;)
            (`c;`button;)
            (`wy;0.0;))
          ))
      (`NO_DISTRESS
       {[x;y;z]
    m:`.(-2_.j.v),`distress`metric
    l:`.(-2_.j.v),`distress`level
    h:`.(-2_.j.v),`distress`horizon
    s:`.(-3_.j.v),`paths.`S,m
    f:`.(-3_.j.v),`paths.`F,m
    H:`.(-3_.j.v),`paths.`H
    e:{[o]
      / e is symbol vector of the selected entities
      / (eventually, this will need to be updated to handle consolidations)
      e::[~_n~t:o`entity_and_accounting_standard; {(!x)@&x[]}{                        x.Entity              }t
          ~_n~t:o`entity_or_portfolio           ; {(!x)@&x[]}{:[x.Display_Entity_Data;x.Entity _di`fill;.()]}t
          ~_n~t:o`treaties_and_products         ; {x.entities@&.j.True=x.entities..j.bg}                     t
                                                  0#` ]
      e }[`.-3_ .j.v]
    if[1<#e;:.j.ok.w .l.ss "More than one entity selected"]
    if[0=#e;:.j.ok.w .l.ss "No entity selected"]
    s[`Entity]:e
    if[(*.m.G[H;(`raxis;s)])~.();:.j.ok.w .l.ss("Distress metric not available for entity &0: &1";e;`.(-2_.j.v),`distress`metric)]
    r:.m.G[H;(`sum_vt;(s;_n;,h))]
    d:r[2;0;0]
    p:&x@f[d;l]
    .[`;(-2_.j.v),y;:;p]
    (`.(-2_.j.v),`paths.`j`Set_)[`Only;(-2_.j.v),`paths;p] }[~:;`NON_DISTRESSED]
       .,(`j
          .((`l;`"NO DISTRESS";)
            (`fill;`h;)
            (`c;`button;)
            (`wy;0.0;))
          ))
      (`NONE
       {(`.(-2_.j.v),`paths.`j`Set_)[`None;(-2_.j.v),`paths;!0]}
       .,(`j
          .((`l;`NONE;)
            (`fill;`h;)
            (`c;`button;)
            (`wy;0.0;))
          ))
      (`COPY
       {.w.cbwrite[,`DFA_;,.,(`Path;(`.(-2_.j.v),`paths)@(`.(-2_.j.v),`paths.`j`Get_)[(-2_.j.v),`paths])]}
       .,(`j
          .((`l;`COPY;)
            (`fill;`h;)
            (`c;`button;)
            (`wy;0.0;))
          ))
      (`PASTE
       {
    if[~`DFA_ _in .w.cbformats[];:.u.beep[]]
    c:.w.cbread `DFA_
    if[~`Path _in !c;:.u.beep[]]
    d:(-2_.j.v),`paths
    j:(-2_.j.v),`paths.`j
    p:c`Path
    p:p@&p _lin `. d
    (`. j,`Set_)[`Only;d;p]}
       .,(`j
          .((`l;`PASTE;)
            (`fill;`h;)
            (`c;`button;)
            (`wy;0.0;))
          ))
      (`PASTE_WITH
       {
    if[~`DFA_ _in .w.cbformats[];:.u.beep[]]
    c:.w.cbread `DFA_
    if[~`Path _in !c;:.u.beep[]]
    d:(-2_.j.v),`paths
    j:(-2_.j.v),`paths.`j
    p:c`Path
    p:p@&p _lin `. d
    (`. j,`Set_)[`With;d;{x@<x}@?p,(`. j,`Get_)[d]]}
       .,(`j
          .((`l;`"PASTE WITH";)
            (`fill;`h;)
            (`c;`button;)
            (`wy;0.0;))
          ))
      (`panel
       .()
       .,(`j
          .((`c;`panel;)
            (`wy;1.0;)
            (`border;0;))
          )))
    .,(`j
       .((`border;0;)
         (`c;`panel;)
         (`wx;0.2;))
       ))
   (`paths
    0 1 2 3 4
    .((`j
       .((`c;`Vector_;)
         (`type;`Path;)
         (`bg
          `scrollbarblue `scrollbarblue `scrollbarblue `scrollbarblue `scrollbarblue
          .())
         (`l;"Paths 5";)
         (`e;0;)
         (`kk;{c:cl .j.v;the[c]'[`With_v`Without_v][|/,//of[c;`true;,.j.v]=`. jd[.j.v],`bg,.j.i][_n;.j.v]};)
         (`wx;0.4;)
         (`pack;1;)
         (`popup
          .((`All;{[x]c:cl v:ad -2_.j.v;of[c;`set_;(`All;v;of[c;`all_;,v])]};)
            (`None;{[x]c:cl v:ad -2_.j.v;of[c;`set_;(`None;v;())]};)
            (`s0;" ";)
            (`Only;{[x]c:cl v:ad -2_.j.v;of[c;`set_;(`Only;v;of[c;`selected_;,v])]};)
            (`Except;{[x]c:cl v:ad -2_.j.v;of[c;`set_;(`Except;v;of[cl v;`all_;,v]_dvl of[c;`selected_;,v])]};)
            (`s1;" ";)
            (`With;{[x]C.Data_.With_v[x;ad -2_.j.v]};)
            (`Without;{[x]C.Data_.Without_v[x;ad -2_.j.v]};)
            (`In;{[x]c:cl v:ad -2_.j.v;s:of[c;`get_;,v];of[c;`set_;(`In;v;s@&s _lin of[c;`selected_;,v])]};)
            (`s2;" ";)
            (`Up;{[x]c:cl v:ad -2_.j.v;of[c;`sort_;(c;v;<:)]};)
            (`Down;{[x]c:cl v:ad -2_.j.v;of[c;`sort_;(c;v;>:)]};)
            (`s3;" ";)
            (`Copy_Selection;{[x]c:cl v:ad -2_.j.v;of[c;`copy_;(c;v)]};)
            (`Paste_Selection;{[x]c:cl v:ad -2_.j.v;of[c;`paste_;(c;v)]};)
            (`s99;" ";)
            (`Copy;{[f;junk]c:name.c v:f .j.v;if[(1~the[c;`alwaysSel])|~empty s:att[v;`s];of[c;`copy;(v;s)]]}[{@[x;-1+#x,:();~:]}-2_];)
            (`Copy_All;{[f;junk]c:name.c v:f .j.v;of[c;`copy_all;(v;)]}[{@[x;-1+#x,:();~:]}-2_];)
            (`S98;" ";)
            (`Ranges;{
   .k.RANGES.functions.a:{[op;all;list]
    new:.k.RANGES.functions[op][all;list]
    if[0=#new
     .k.RANGES.panel.message:"At least one Path must be selected"
     :_n
    ]
    .k[`r;`o;`o;`paths;`paths.;`j;`bg]:.j[`False`True]@.k[`r;`o;`o;`paths;`paths] _lin new
    .k[`r;`o;`o;`paths;`paths.;`j;`s]:!0
    .j.d`.k.RANGES
   }
   .k.RANGES.functions.Only   :{[all;list] all@& all _lin list}
   .k.RANGES.functions.Except :{[all;list] all@&~all _lin list}
   .k.RANGES.functions.With   :{[all;list] prev:all@&.j.True=.k[`r;`o;`o;`paths;`paths.;`j;`bg]; all@&all _lin list,prev}
   .k.RANGES.functions.Without:{[all;list] prev:all@&.j.True=.k[`r;`o;`o;`paths;`paths.;`j;`bg]; prev _dvl list}
   .k.RANGES.functions.In     :{[all;list] prev:all@&.j.True=.k[`r;`o;`o;`paths;`paths.;`j;`bg]; prev@&prev _lin list}
   .k.RANGES.functions.main:{
    op:*-1#.j.v
    if[op _in`Cancel`RANGES;.j.d`.k.RANGES;:_n]
    r:.u.check_path_list[`paths;0I;_n;.k.RANGES.panel.text]
    if[1~**r
     .k.RANGES.panel.message:.l.ss r[0;1]
     :_n
    ]
    all:.k[`r;`o;`o;`paths;`paths]
    list:@[.u.string2intlist;.k.RANGES.panel.text;:]
    if[*list
     .k.RANGES.panel.message:list 1
     :_n
    ]
    if[#invalid:list[1;&~list[1] _lin all]
     .j.ok.W .l.ss("The following invalid paths will be ignored:\n&0";.u.bunch_numbers[0I;invalid])
    ]
    .k.RANGES.functions.a[op;all;list 1]
   }
   .k.RANGES[`Only`Except`With`Without`In`Cancel]:.k.RANGES.functions.main
   .k.RANGES[~`Only`Except`With`Without`In`Cancel;`j;`async]:2
   .k.RANGES[~`Only`Except`With`Without`In`Cancel;`j;`mnem]:`o`e`w`t`i`c
   .k.RANGES..j.close:.k.RANGES.functions.main
   .k.RANGES..j.modal:1
   .k.RANGES.panel.label:"Ranges are separated by spaces, commas or newlines.\nExample: \"0-4,7-21,1999-2010\"."
   .k.RANGES.panel.message:""
   .k.RANGES.panel.text:""
   .k.RANGES.panel.label..j.c:`label
   .k.RANGES.panel.text..j.c:`text
   .k.RANGES.panel.message..j.c:`label
   .k.RANGES.panel.message..j.fg:`r
   .k.RANGES.panel.text..j.l:""
   .k.RANGES.panel.text..j.border:0
   .k.RANGES.panel.text..j.save:1
   .k.RANGES.panel.text..j.echo:0	/ this is necessary to prevent lost character when typing quickly with save:1
   .k.RANGES.panel..j.border:0
   .k.RANGES.panel..j.c:`panel
   .k.RANGES.panel..j.a:`label`text`message
   .k.RANGES..j.c:`panel
   .k.RANGES..j.a:(`panel;`Only`Except`With`Without`In`Cancel)
   .k.RANGES..j.on:`.k.r
   .k.RANGES..j.l:"Specify Ranges of Paths"
   .k.RANGES.panel.text:.u.bunch_numbers[0I;.k[`r;`o;`o;`paths;`paths]@&.j.True=.k[`r;`o;`o;`paths;`paths.;`j;`bg]]
   .k.RANGES.panel.message:""
   .j.c `.k.RANGES
   .k.RANGES.panel.text..j.s:!#.k.RANGES.panel.text
  };))
          .,(`j
             .,(`ne
                ((,`All
                  ,`None
                  ,`s0
                  ,`Only
                  ,`Except
                  ,`s1
                  ,`With
                  ,`Without
                  ,`In
                  ,`s2
                  ,`Up
                  ,`Down
                  ,`s3
                  ,`Copy_Selection
                  ,`Paste_Selection
                  ,`Copy
                  ,`Copy_All
                  ,`s99
                  ,`S98
                  ,`Ranges)
                 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0)
                )
             ))
         (`Set;{.[`;(-1_.j.v),`paths.`j`l;:;(.l.ss"Paths")," ",$#(`.(-1_.j.v),`paths.`j`Get_)@.j.v]};)
         (`krd;{
 C.Data.Sel[]
 c:cl v:.j.v
 n:`. jd[v],`popup.`j`ne
 n[1;(,/*n)?/:!*of[c;`operations_;,v]]:1
 m:`$($,/*n),\:"__"
 f:.+(m;the[c]'m);f:f _di(!f)@&~7=4::'f[]
 n[1;m?/:!f]:f[]@\:v
 .[`;jd[v],`popup.`j`ne;:;n]
};)
         (`Set_;{[f;v;s]
 b:of[cl v;;,v]'`false`true`null
 s::[~0~att[v;`All];s;(#s)~#`. v;!0;s]
 s::[~0~att[v;`None];s;~#s;!#`. v;s]
 w:jd v;d:`. v;if[_n~bg:`. w,`bg;bg:(#d)#*b];i:&~bg _lin b
 :[1~att[v;`Check]
  do[1;.[`;v;:;@[(#d)#*b;s;:;b 1]];fire_t v]
  do[1;.[`;w,`bg;:;@[@[@[(#d)#*b;s;:;b 1];&d~'_n;:;b 2];i;:;bg i]];fire_t w,`bg]]
 .[`;w,`s;:;_n]
 user[`Set;f;v;s]
};)
         (`Get_;{[v]&of[cl v;`bool_;,v]};)
         (`s;;))
       )
      (`V;{[x;y]:[+/U.True=y.j.bg;_n;"Please select at least one path"]};))))
 .((`I
    .((`US_Statutory_Capital_and_Surplus_to_Risk_Based_Capital_Ratio;1.0;)
      (`Standard_and_Poors_AAA_Redundancy_Ratio;0.5;)
      (`Standard_and_Poors_AA_Redundancy_Ratio;0.5;)
      (`Standard_and_Poors_A_Redundancy_Ratio;0.5;)
      (`Standard_and_Poors_BBB_Redundancy_Ratio;0.5;)
      (`AM_Best_Capital_Adequacy_Ratio;1.0;))
    )
   (`O
    .((`US_Statutory_Capital_and_Surplus_to_Risk_Based_Capital_Ratio
       0 0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1 1.05 1.1 1.15 1.2 1.25 1.3 1.35 1.4 1.45 1.5 1.55 1.6 1.65 1.7 1.75 1.8 1.85 1.9 1.95 2 2.05 2.1 2.15 2.2 2.25 2.3 2.35 2.4 2.45 2.5 2.55 2.6 2.65 2.7 2.75 2.8 2.85 2.9 2.95 3 3.05 3.1 3.15 3.2 3.25 3.3 3.35 3.4 3.45 3.5 3.55 3.6 3.65 3.7 3.75 3.8 3.85 3.9 3.95 4 4.05 4.1 4.15 4.2 4.25 4.3 4.35 4.4 4.45 4.5 4.55 4.6 4.65 4.7 4.75 4.8 4.85 4.9 4.95 5
       )
      (`Standard_and_Poors_AAA_Redundancy_Ratio
       0 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1
       )
      (`Standard_and_Poors_AA_Redundancy_Ratio
       0 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1
       )
      (`Standard_and_Poors_A_Redundancy_Ratio
       0 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1
       )
      (`Standard_and_Poors_BBB_Redundancy_Ratio
       0 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1
       )
      (`AM_Best_Capital_Adequacy_Ratio
       0 0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1 1.05 1.1 1.15 1.2 1.25 1.3 1.35 1.4 1.45 1.5 1.55 1.6 1.65 1.7 1.75 1.8 1.85 1.9 1.95 2 2.05 2.1 2.15 2.2 2.25 2.3 2.35 2.4 2.45 2.5 2.55 2.6 2.65 2.7 2.75 2.8 2.85 2.9 2.95 3 3.05 3.1 3.15 3.2 3.25 3.3 3.35 3.4 3.45 3.5 3.55 3.6 3.65 3.7 3.75 3.8 3.85 3.9 3.95 4 4.05 4.1 4.15 4.2 4.25 4.3 4.35 4.4 4.45 4.5 4.55 4.6 4.65 4.7 4.75 4.8 4.85 4.9 4.95 5
       ))
    )
   (`L
    .((`US_Statutory_Capital_and_Surplus_to_Risk_Based_Capital_Ratio
       (0 0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1 1.05 1.1 1.15 1.2 1.25 1.3 1.35 1.4 1.45 1.5 1.55 1.6 1.65 1.7 1.75 1.8 1.85 1.9 1.95 2 2.05 2.1 2.15 2.2 2.25 2.3 2.35 2.4 2.45 2.5 2.55 2.6 2.65 2.7 2.75 2.8 2.85 2.9 2.95 3 3.05 3.1 3.15 3.2 3.25 3.3 3.35 3.4 3.45 3.5 3.55 3.6 3.65 3.7 3.75 3.8 3.85 3.9 3.95 4 4.05 4.1 4.15 4.2 4.25 4.3 4.35 4.4 4.45 4.5 4.55 4.6 4.65 4.7 4.75 4.8 4.85 4.9 4.95 5
        ("0.00"
         "0.05"
         "0.10"
         "0.15"
         "0.20"
         "0.25"
         "0.30"
         "0.35"
         "0.40"
         "0.45"
         "0.50"
         "0.55"
         "0.60"
         "0.65"
         "0.70"
         "0.75"
         "0.80"
         "0.85"
         "0.90"
         "0.95"
         "1.00"
         "1.05"
         "1.10"
         "1.15"
         "1.20"
         "1.25"
         "1.30"
         "1.35"
         "1.40"
         "1.45"
         "1.50"
         "1.55"
         "1.60"
         "1.65"
         "1.70"
         "1.75"
         "1.80"
         "1.85"
         "1.90"
         "1.95"
         "2.00"
         "2.05"
         "2.10"
         "2.15"
         "2.20"
         "2.25"
         "2.30"
         "2.35"
         "2.40"
         "2.45"
         "2.50"
         "2.55"
         "2.60"
         "2.65"
         "2.70"
         "2.75"
         "2.80"
         "2.85"
         "2.90"
         "2.95"
         "3.00"
         "3.05"
         "3.10"
         "3.15"
         "3.20"
         "3.25"
         "3.30"
         "3.35"
         "3.40"
         "3.45"
         "3.50"
         "3.55"
         "3.60"
         "3.65"
         "3.70"
         "3.75"
         "3.80"
         "3.85"
         "3.90"
         "3.95"
         "4.00"
         "4.05"
         "4.10"
         "4.15"
         "4.20"
         "4.25"
         "4.30"
         "4.35"
         "4.40"
         "4.45"
         "4.50"
         "4.55"
         "4.60"
         "4.65"
         "4.70"
         "4.75"
         "4.80"
         "4.85"
         "4.90"
         "4.95"
         "5.00"))
       )
      (`Standard_and_Poors_AAA_Redundancy_Ratio
       (0 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1
        ("0.00"
         "0.01"
         "0.02"
         "0.03"
         "0.04"
         "0.05"
         "0.06"
         "0.07"
         "0.08"
         "0.09"
         "0.10"
         "0.11"
         "0.12"
         "0.13"
         "0.14"
         "0.15"
         "0.16"
         "0.17"
         "0.18"
         "0.19"
         "0.20"
         "0.21"
         "0.22"
         "0.23"
         "0.24"
         "0.25"
         "0.26"
         "0.27"
         "0.28"
         "0.29"
         "0.30"
         "0.31"
         "0.32"
         "0.33"
         "0.34"
         "0.35"
         "0.36"
         "0.37"
         "0.38"
         "0.39"
         "0.40"
         "0.41"
         "0.42"
         "0.43"
         "0.44"
         "0.45"
         "0.46"
         "0.47"
         "0.48"
         "0.49"
         "0.50"
         "0.51"
         "0.52"
         "0.53"
         "0.54"
         "0.55"
         "0.56"
         "0.57"
         "0.58"
         "0.59"
         "0.60"
         "0.61"
         "0.62"
         "0.63"
         "0.64"
         "0.65"
         "0.66"
         "0.67"
         "0.68"
         "0.69"
         "0.70"
         "0.71"
         "0.72"
         "0.73"
         "0.74"
         "0.75"
         "0.76"
         "0.77"
         "0.78"
         "0.79"
         "0.80"
         "0.81"
         "0.82"
         "0.83"
         "0.84"
         "0.85"
         "0.86"
         "0.87"
         "0.88"
         "0.89"
         "0.90"
         "0.91"
         "0.92"
         "0.93"
         "0.94"
         "0.95"
         "0.96"
         "0.97"
         "0.98"
         "0.99"
         "1.00"))
       )
      (`Standard_and_Poors_AA_Redundancy_Ratio
       (0 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1
        ("0.00"
         "0.01"
         "0.02"
         "0.03"
         "0.04"
         "0.05"
         "0.06"
         "0.07"
         "0.08"
         "0.09"
         "0.10"
         "0.11"
         "0.12"
         "0.13"
         "0.14"
         "0.15"
         "0.16"
         "0.17"
         "0.18"
         "0.19"
         "0.20"
         "0.21"
         "0.22"
         "0.23"
         "0.24"
         "0.25"
         "0.26"
         "0.27"
         "0.28"
         "0.29"
         "0.30"
         "0.31"
         "0.32"
         "0.33"
         "0.34"
         "0.35"
         "0.36"
         "0.37"
         "0.38"
         "0.39"
         "0.40"
         "0.41"
         "0.42"
         "0.43"
         "0.44"
         "0.45"
         "0.46"
         "0.47"
         "0.48"
         "0.49"
         "0.50"
         "0.51"
         "0.52"
         "0.53"
         "0.54"
         "0.55"
         "0.56"
         "0.57"
         "0.58"
         "0.59"
         "0.60"
         "0.61"
         "0.62"
         "0.63"
         "0.64"
         "0.65"
         "0.66"
         "0.67"
         "0.68"
         "0.69"
         "0.70"
         "0.71"
         "0.72"
         "0.73"
         "0.74"
         "0.75"
         "0.76"
         "0.77"
         "0.78"
         "0.79"
         "0.80"
         "0.81"
         "0.82"
         "0.83"
         "0.84"
         "0.85"
         "0.86"
         "0.87"
         "0.88"
         "0.89"
         "0.90"
         "0.91"
         "0.92"
         "0.93"
         "0.94"
         "0.95"
         "0.96"
         "0.97"
         "0.98"
         "0.99"
         "1.00"))
       )
      (`Standard_and_Poors_A_Redundancy_Ratio
       (0 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1
        ("0.00"
         "0.01"
         "0.02"
         "0.03"
         "0.04"
         "0.05"
         "0.06"
         "0.07"
         "0.08"
         "0.09"
         "0.10"
         "0.11"
         "0.12"
         "0.13"
         "0.14"
         "0.15"
         "0.16"
         "0.17"
         "0.18"
         "0.19"
         "0.20"
         "0.21"
         "0.22"
         "0.23"
         "0.24"
         "0.25"
         "0.26"
         "0.27"
         "0.28"
         "0.29"
         "0.30"
         "0.31"
         "0.32"
         "0.33"
         "0.34"
         "0.35"
         "0.36"
         "0.37"
         "0.38"
         "0.39"
         "0.40"
         "0.41"
         "0.42"
         "0.43"
         "0.44"
         "0.45"
         "0.46"
         "0.47"
         "0.48"
         "0.49"
         "0.50"
         "0.51"
         "0.52"
         "0.53"
         "0.54"
         "0.55"
         "0.56"
         "0.57"
         "0.58"
         "0.59"
         "0.60"
         "0.61"
         "0.62"
         "0.63"
         "0.64"
         "0.65"
         "0.66"
         "0.67"
         "0.68"
         "0.69"
         "0.70"
         "0.71"
         "0.72"
         "0.73"
         "0.74"
         "0.75"
         "0.76"
         "0.77"
         "0.78"
         "0.79"
         "0.80"
         "0.81"
         "0.82"
         "0.83"
         "0.84"
         "0.85"
         "0.86"
         "0.87"
         "0.88"
         "0.89"
         "0.90"
         "0.91"
         "0.92"
         "0.93"
         "0.94"
         "0.95"
         "0.96"
         "0.97"
         "0.98"
         "0.99"
         "1.00"))
       )
      (`Standard_and_Poors_BBB_Redundancy_Ratio
       (0 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1
        ("0.00"
         "0.01"
         "0.02"
         "0.03"
         "0.04"
         "0.05"
         "0.06"
         "0.07"
         "0.08"
         "0.09"
         "0.10"
         "0.11"
         "0.12"
         "0.13"
         "0.14"
         "0.15"
         "0.16"
         "0.17"
         "0.18"
         "0.19"
         "0.20"
         "0.21"
         "0.22"
         "0.23"
         "0.24"
         "0.25"
         "0.26"
         "0.27"
         "0.28"
         "0.29"
         "0.30"
         "0.31"
         "0.32"
         "0.33"
         "0.34"
         "0.35"
         "0.36"
         "0.37"
         "0.38"
         "0.39"
         "0.40"
         "0.41"
         "0.42"
         "0.43"
         "0.44"
         "0.45"
         "0.46"
         "0.47"
         "0.48"
         "0.49"
         "0.50"
         "0.51"
         "0.52"
         "0.53"
         "0.54"
         "0.55"
         "0.56"
         "0.57"
         "0.58"
         "0.59"
         "0.60"
         "0.61"
         "0.62"
         "0.63"
         "0.64"
         "0.65"
         "0.66"
         "0.67"
         "0.68"
         "0.69"
         "0.70"
         "0.71"
         "0.72"
         "0.73"
         "0.74"
         "0.75"
         "0.76"
         "0.77"
         "0.78"
         "0.79"
         "0.80"
         "0.81"
         "0.82"
         "0.83"
         "0.84"
         "0.85"
         "0.86"
         "0.87"
         "0.88"
         "0.89"
         "0.90"
         "0.91"
         "0.92"
         "0.93"
         "0.94"
         "0.95"
         "0.96"
         "0.97"
         "0.98"
         "0.99"
         "1.00"))
       )
      (`AM_Best_Capital_Adequacy_Ratio
       (0 0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1 1.05 1.1 1.15 1.2 1.25 1.3 1.35 1.4 1.45 1.5 1.55 1.6 1.65 1.7 1.75 1.8 1.85 1.9 1.95 2 2.05 2.1 2.15 2.2 2.25 2.3 2.35 2.4 2.45 2.5 2.55 2.6 2.65 2.7 2.75 2.8 2.85 2.9 2.95 3 3.05 3.1 3.15 3.2 3.25 3.3 3.35 3.4 3.45 3.5 3.55 3.6 3.65 3.7 3.75 3.8 3.85 3.9 3.95 4 4.05 4.1 4.15 4.2 4.25 4.3 4.35 4.4 4.45 4.5 4.55 4.6 4.65 4.7 4.75 4.8 4.85 4.9 4.95 5
        ("0.00"
         "0.05"
         "0.10"
         "0.15"
         "0.20"
         "0.25"
         "0.30"
         "0.35"
         "0.40"
         "0.45"
         "0.50"
         "0.55"
         "0.60"
         "0.65"
         "0.70"
         "0.75"
         "0.80"
         "0.85"
         "0.90"
         "0.95"
         "1.00"
         "1.05"
         "1.10"
         "1.15"
         "1.20"
         "1.25"
         "1.30"
         "1.35"
         "1.40"
         "1.45"
         "1.50"
         "1.55"
         "1.60"
         "1.65"
         "1.70"
         "1.75"
         "1.80"
         "1.85"
         "1.90"
         "1.95"
         "2.00"
         "2.05"
         "2.10"
         "2.15"
         "2.20"
         "2.25"
         "2.30"
         "2.35"
         "2.40"
         "2.45"
         "2.50"
         "2.55"
         "2.60"
         "2.65"
         "2.70"
         "2.75"
         "2.80"
         "2.85"
         "2.90"
         "2.95"
         "3.00"
         "3.05"
         "3.10"
         "3.15"
         "3.20"
         "3.25"
         "3.30"
         "3.35"
         "3.40"
         "3.45"
         "3.50"
         "3.55"
         "3.60"
         "3.65"
         "3.70"
         "3.75"
         "3.80"
         "3.85"
         "3.90"
         "3.95"
         "4.00"
         "4.05"
         "4.10"
         "4.15"
         "4.20"
         "4.25"
         "4.30"
         "4.35"
         "4.40"
         "4.45"
         "4.50"
         "4.55"
         "4.60"
         "4.65"
         "4.70"
         "4.75"
         "4.80"
         "4.85"
         "4.90"
         "4.95"
         "5.00"))
       ))
    )
   (`S
    .((`US_Statutory_Capital_and_Surplus_to_Risk_Based_Capital_Ratio
       .((`Regulatory_Submodule
          ,`RBC
          )
         (`Item
          ,`Minimum_PHS_to_RBC_Ratio_Intrayear
          ))
       )
      (`Standard_and_Poors_AAA_Redundancy_Ratio
       .((`Regulatory_Submodule
          ,`SaP
          )
         (`Confidence_Level
          ,`AAA
          )
         (`Item
          ,`Redundancy_Ratio
          )
         (`Timing
          ,`Final
          ))
       )
      (`Standard_and_Poors_AA_Redundancy_Ratio
       .((`Regulatory_Submodule
          ,`SaP
          )
         (`Confidence_Level
          ,`AA
          )
         (`Item
          ,`Redundancy_Ratio
          )
         (`Timing
          ,`Final
          ))
       )
      (`Standard_and_Poors_A_Redundancy_Ratio
       .((`Regulatory_Submodule
          ,`SaP
          )
         (`Confidence_Level
          ,`A
          )
         (`Item
          ,`Redundancy_Ratio
          )
         (`Timing
          ,`Final
          ))
       )
      (`Standard_and_Poors_BBB_Redundancy_Ratio
       .((`Regulatory_Submodule
          ,`SaP
          )
         (`Confidence_Level
          ,`BBB
          )
         (`Item
          ,`Redundancy_Ratio
          )
         (`Timing
          ,`Final
          ))
       )
      (`AM_Best_Capital_Adequacy_Ratio
       .((`Regulatory_Submodule
          ,`BCAR
          )
         (`Item
          ,`Capital_Adequacy_Ratio
          )
         (`Timing
          ,`Final
          ))
       ))
    )
   (`F
    .((`US_Statutory_Capital_and_Surplus_to_Risk_Based_Capital_Ratio;<;)
      (`Standard_and_Poors_AAA_Redundancy_Ratio;<;)
      (`Standard_and_Poors_AA_Redundancy_Ratio;<;)
      (`Standard_and_Poors_A_Redundancy_Ratio;<;)
      (`Standard_and_Poors_BBB_Redundancy_Ratio;<;)
      (`AM_Best_Capital_Adequacy_Ratio;<;))
    )
   (`C
    .((`US_Statutory_Capital_and_Surplus_to_Risk_Based_Capital_Ratio;1;)
      (`Standard_and_Poors_AAA_Redundancy_Ratio;1;)
      (`Standard_and_Poors_AA_Redundancy_Ratio;1;)
      (`Standard_and_Poors_A_Redundancy_Ratio;1;)
      (`Standard_and_Poors_BBB_Redundancy_Ratio;1;)
      (`AM_Best_Capital_Adequacy_Ratio;1;))
    )
   (`H;568;)
   (`j
    .((`l;`Paths;)
      (`c;`panel;)
      (`a
       ,`distress `flags `paths
       ))
    )))


p: ser[0]
p.: ser[1]
p..j.c: `panel
p..j.close:{_exit 0}
p..j.xy:(600 600)
.j.Java{
  .j.c `p
};
p..j.z: {
  if[1~.k[`autoExit];_exit 0]
  }